name = "nikcli-web"
main = "./dist/_worker.js"
compatibility_date = "2025-01-25"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSION"
id = "9472fcfbe18245438b2d4af7cbdaef81"
