name = "nikcli-web"
main = "./dist/_worker.js"
compatibility_date = "2025-01-25"

[assets]
directory = "./dist"
binding = "ASSETS"

[[kv_namespaces]]
binding = "SESSIONS"
id = "e9dfbfcd44c14909b03cef0629b4f80f"

[[kv_namespaces]]
binding = "USERS"
id = "bb2d5e50ff1644b482c71b7355a7684c"
