// Generated by @nikcli-ai/httpapi-codegen. Do not edit.
import type { Effect, Stream } from "effect"
import type { HttpApiClient } from "effect/unstable/httpapi"
import type { PublicApi } from "../../public"

type RawClient = HttpApiClient.ForApi<typeof PublicApi>
type EffectValue<A> = A extends Effect.Effect<infer Success, any, any> ? Success : never
type StreamValue<A> = A extends Stream.Stream<infer Success, any, any> ? Success : never

export type Endpoint0_0Output = EffectValue<ReturnType<RawClient["top-level"]["dispose"]>>
export type TopLevelDisposeOperation<E = never> = () => Effect.Effect<Endpoint0_0Output, E>

export type Endpoint0_1Output = EffectValue<ReturnType<RawClient["top-level"]["path"]>>
export type TopLevelPathOperation<E = never> = () => Effect.Effect<Endpoint0_1Output, E>

export type Endpoint0_2Output = EffectValue<ReturnType<RawClient["top-level"]["vcs"]>>
export type TopLevelVcsOperation<E = never> = () => Effect.Effect<Endpoint0_2Output, E>

export type Endpoint0_3Output = EffectValue<ReturnType<RawClient["top-level"]["vcsStatus"]>>
export type TopLevelVcsStatusOperation<E = never> = () => Effect.Effect<Endpoint0_3Output, E>

export type Endpoint0_4Output = EffectValue<ReturnType<RawClient["top-level"]["vcsDiffRaw"]>>
export type TopLevelVcsDiffRawOperation<E = never> = () => Effect.Effect<Endpoint0_4Output, E>

type Endpoint0_5Request = Parameters<RawClient["top-level"]["vcsApply"]>[0]
export type Endpoint0_5Input = { readonly patch: Endpoint0_5Request["payload"]["patch"] }
export type Endpoint0_5Output = EffectValue<ReturnType<RawClient["top-level"]["vcsApply"]>>
export type TopLevelVcsApplyOperation<E = never> = (input: Endpoint0_5Input) => Effect.Effect<Endpoint0_5Output, E>

export type Endpoint0_6Output = EffectValue<ReturnType<RawClient["top-level"]["command"]>>
export type TopLevelCommandOperation<E = never> = () => Effect.Effect<Endpoint0_6Output, E>

export type Endpoint0_7Output = EffectValue<ReturnType<RawClient["top-level"]["agent"]>>
export type TopLevelAgentOperation<E = never> = () => Effect.Effect<Endpoint0_7Output, E>

export type Endpoint0_8Output = EffectValue<ReturnType<RawClient["top-level"]["skill"]>>
export type TopLevelSkillOperation<E = never> = () => Effect.Effect<Endpoint0_8Output, E>

export type Endpoint0_9Output = EffectValue<ReturnType<RawClient["top-level"]["lsp"]>>
export type TopLevelLspOperation<E = never> = () => Effect.Effect<Endpoint0_9Output, E>

export type Endpoint0_10Output = EffectValue<ReturnType<RawClient["top-level"]["formatter"]>>
export type TopLevelFormatterOperation<E = never> = () => Effect.Effect<Endpoint0_10Output, E>

export interface TopLevelApi<E = never> {
  readonly dispose: TopLevelDisposeOperation<E>
  readonly path: TopLevelPathOperation<E>
  readonly vcs: TopLevelVcsOperation<E>
  readonly vcsStatus: TopLevelVcsStatusOperation<E>
  readonly vcsDiffRaw: TopLevelVcsDiffRawOperation<E>
  readonly vcsApply: TopLevelVcsApplyOperation<E>
  readonly command: TopLevelCommandOperation<E>
  readonly agent: TopLevelAgentOperation<E>
  readonly skill: TopLevelSkillOperation<E>
  readonly lsp: TopLevelLspOperation<E>
  readonly formatter: TopLevelFormatterOperation<E>
}

export type Endpoint1_0Output = EffectValue<ReturnType<RawClient["analytics"]["global"]>>
export type AnalyticsGlobalOperation<E = never> = () => Effect.Effect<Endpoint1_0Output, E>

type Endpoint1_1Request = Parameters<RawClient["analytics"]["daily"]>[0]
export type Endpoint1_1Input = {
  readonly from?: Endpoint1_1Request["query"]["from"]
  readonly to?: Endpoint1_1Request["query"]["to"]
  readonly days?: Endpoint1_1Request["query"]["days"]
}
export type Endpoint1_1Output = EffectValue<ReturnType<RawClient["analytics"]["daily"]>>
export type AnalyticsDailyOperation<E = never> = (input?: Endpoint1_1Input) => Effect.Effect<Endpoint1_1Output, E>

type Endpoint1_2Request = Parameters<RawClient["analytics"]["session"]>[0]
export type Endpoint1_2Input = { readonly sessionID: Endpoint1_2Request["params"]["sessionID"] }
export type Endpoint1_2Output = EffectValue<ReturnType<RawClient["analytics"]["session"]>>
export type AnalyticsSessionOperation<E = never> = (input: Endpoint1_2Input) => Effect.Effect<Endpoint1_2Output, E>

export type Endpoint1_3Output = EffectValue<ReturnType<RawClient["analytics"]["sessions"]>>
export type AnalyticsSessionsOperation<E = never> = () => Effect.Effect<Endpoint1_3Output, E>

export type Endpoint1_4Output = EffectValue<ReturnType<RawClient["analytics"]["leaderboard"]>>
export type AnalyticsLeaderboardOperation<E = never> = () => Effect.Effect<Endpoint1_4Output, E>

export interface AnalyticsApi<E = never> {
  readonly global: AnalyticsGlobalOperation<E>
  readonly daily: AnalyticsDailyOperation<E>
  readonly session: AnalyticsSessionOperation<E>
  readonly sessions: AnalyticsSessionsOperation<E>
  readonly leaderboard: AnalyticsLeaderboardOperation<E>
}

type Endpoint2_0Request = Parameters<RawClient["app"]["log"]>[0]
export type Endpoint2_0Input = {
  readonly service: Endpoint2_0Request["payload"]["service"]
  readonly level: Endpoint2_0Request["payload"]["level"]
  readonly message: Endpoint2_0Request["payload"]["message"]
  readonly extra?: Endpoint2_0Request["payload"]["extra"]
}
export type Endpoint2_0Output = EffectValue<ReturnType<RawClient["app"]["log"]>>
export type AppLogOperation<E = never> = (input: Endpoint2_0Input) => Effect.Effect<Endpoint2_0Output, E>

type Endpoint2_1Request = Parameters<RawClient["app"]["skillCreate"]>[0]
export type Endpoint2_1Input = {
  readonly name: Endpoint2_1Request["payload"]["name"]
  readonly description: Endpoint2_1Request["payload"]["description"]
  readonly category?: Endpoint2_1Request["payload"]["category"]
  readonly tags?: Endpoint2_1Request["payload"]["tags"]
  readonly content?: Endpoint2_1Request["payload"]["content"]
  readonly scope?: Endpoint2_1Request["payload"]["scope"]
}
export type Endpoint2_1Output = EffectValue<ReturnType<RawClient["app"]["skillCreate"]>>
export type AppSkillCreateOperation<E = never> = (input: Endpoint2_1Input) => Effect.Effect<Endpoint2_1Output, E>

type Endpoint2_2Request = Parameters<RawClient["app"]["skillDelete"]>[0]
export type Endpoint2_2Input = { readonly name: Endpoint2_2Request["params"]["name"] }
export type Endpoint2_2Output = EffectValue<ReturnType<RawClient["app"]["skillDelete"]>>
export type AppSkillDeleteOperation<E = never> = (input: Endpoint2_2Input) => Effect.Effect<Endpoint2_2Output, E>

export interface AppApi<E = never> {
  readonly log: AppLogOperation<E>
  readonly skillCreate: AppSkillCreateOperation<E>
  readonly skillDelete: AppSkillDeleteOperation<E>
}

export type Endpoint3_0Output = EffectValue<ReturnType<RawClient["brain"]["status"]>>
export type BrainStatusOperation<E = never> = () => Effect.Effect<Endpoint3_0Output, E>

type Endpoint3_1Request = Parameters<RawClient["brain"]["trigger"]>[0]
export type Endpoint3_1Input = { readonly force?: Endpoint3_1Request["payload"]["force"] }
export type Endpoint3_1Output = EffectValue<ReturnType<RawClient["brain"]["trigger"]>>
export type BrainTriggerOperation<E = never> = (input?: Endpoint3_1Input) => Effect.Effect<Endpoint3_1Output, E>

export interface BrainApi<E = never> {
  readonly status: BrainStatusOperation<E>
  readonly trigger: BrainTriggerOperation<E>
}

export type Endpoint4_0Output = EffectValue<ReturnType<RawClient["config"]["get"]>>
export type ConfigGetOperation<E = never> = () => Effect.Effect<Endpoint4_0Output, E>

type Endpoint4_1Request = Parameters<RawClient["config"]["update"]>[0]
export type Endpoint4_1Input = { readonly payload: Endpoint4_1Request["payload"] }
export type Endpoint4_1Output = EffectValue<ReturnType<RawClient["config"]["update"]>>
export type ConfigUpdateOperation<E = never> = (input: Endpoint4_1Input) => Effect.Effect<Endpoint4_1Output, E>

export type Endpoint4_2Output = EffectValue<ReturnType<RawClient["config"]["providers"]>>
export type ConfigProvidersOperation<E = never> = () => Effect.Effect<Endpoint4_2Output, E>

export interface ConfigApi<E = never> {
  readonly get: ConfigGetOperation<E>
  readonly update: ConfigUpdateOperation<E>
  readonly providers: ConfigProvidersOperation<E>
}

export type Endpoint5_0Output = EffectValue<ReturnType<RawClient["connectors"]["status"]>>
export type ConnectorsStatusOperation<E = never> = () => Effect.Effect<Endpoint5_0Output, E>

type Endpoint5_1Request = Parameters<RawClient["connectors"]["authSet"]>[0]
export type Endpoint5_1Input = {
  readonly name: Endpoint5_1Request["params"]["name"]
  readonly payload: Endpoint5_1Request["payload"]
}
export type Endpoint5_1Output = EffectValue<ReturnType<RawClient["connectors"]["authSet"]>>
export type ConnectorsAuthSetOperation<E = never> = (input: Endpoint5_1Input) => Effect.Effect<Endpoint5_1Output, E>

type Endpoint5_2Request = Parameters<RawClient["connectors"]["authRemove"]>[0]
export type Endpoint5_2Input = { readonly name: Endpoint5_2Request["params"]["name"] }
export type Endpoint5_2Output = EffectValue<ReturnType<RawClient["connectors"]["authRemove"]>>
export type ConnectorsAuthRemoveOperation<E = never> = (input: Endpoint5_2Input) => Effect.Effect<Endpoint5_2Output, E>

type Endpoint5_3Request = Parameters<RawClient["connectors"]["invalidate"]>[0]
export type Endpoint5_3Input = { readonly name?: Endpoint5_3Request["payload"]["name"] }
export type Endpoint5_3Output = EffectValue<ReturnType<RawClient["connectors"]["invalidate"]>>
export type ConnectorsInvalidateOperation<E = never> = (input?: Endpoint5_3Input) => Effect.Effect<Endpoint5_3Output, E>

export interface ConnectorsApi<E = never> {
  readonly status: ConnectorsStatusOperation<E>
  readonly authSet: ConnectorsAuthSetOperation<E>
  readonly authRemove: ConnectorsAuthRemoveOperation<E>
  readonly invalidate: ConnectorsInvalidateOperation<E>
}

export type Endpoint6_0Output = EffectValue<ReturnType<RawClient["doctor"]["run"]>>
export type DoctorRunOperation<E = never> = () => Effect.Effect<Endpoint6_0Output, E>

export interface DoctorApi<E = never> {
  readonly run: DoctorRunOperation<E>
}

export type Endpoint7_0Output = EffectValue<ReturnType<RawClient["experimental"]["toolIDs"]>>
export type ExperimentalToolIDsOperation<E = never> = () => Effect.Effect<Endpoint7_0Output, E>

type Endpoint7_1Request = Parameters<RawClient["experimental"]["tools"]>[0]
export type Endpoint7_1Input = {
  readonly provider: Endpoint7_1Request["query"]["provider"]
  readonly model: Endpoint7_1Request["query"]["model"]
}
export type Endpoint7_1Output = EffectValue<ReturnType<RawClient["experimental"]["tools"]>>
export type ExperimentalToolsOperation<E = never> = (input: Endpoint7_1Input) => Effect.Effect<Endpoint7_1Output, E>

type Endpoint7_2Request = Parameters<RawClient["experimental"]["worktreeCreate"]>[0]
export type Endpoint7_2Input = {
  readonly name?: Endpoint7_2Request["payload"]["name"]
  readonly branch?: Endpoint7_2Request["payload"]["branch"]
  readonly branchPrefix?: Endpoint7_2Request["payload"]["branchPrefix"]
  readonly baseBranch?: Endpoint7_2Request["payload"]["baseBranch"]
  readonly remote?: Endpoint7_2Request["payload"]["remote"]
  readonly startCommand?: Endpoint7_2Request["payload"]["startCommand"]
}
export type Endpoint7_2Output = EffectValue<ReturnType<RawClient["experimental"]["worktreeCreate"]>>
export type ExperimentalWorktreeCreateOperation<E = never> = (
  input?: Endpoint7_2Input,
) => Effect.Effect<Endpoint7_2Output, E>

export type Endpoint7_3Output = EffectValue<ReturnType<RawClient["experimental"]["worktree"]>>
export type ExperimentalWorktreeOperation<E = never> = () => Effect.Effect<Endpoint7_3Output, E>

type Endpoint7_4Request = Parameters<RawClient["experimental"]["worktreeRemove"]>[0]
export type Endpoint7_4Input = { readonly directory: Endpoint7_4Request["payload"]["directory"] }
export type Endpoint7_4Output = EffectValue<ReturnType<RawClient["experimental"]["worktreeRemove"]>>
export type ExperimentalWorktreeRemoveOperation<E = never> = (
  input: Endpoint7_4Input,
) => Effect.Effect<Endpoint7_4Output, E>

type Endpoint7_5Request = Parameters<RawClient["experimental"]["worktreeReset"]>[0]
export type Endpoint7_5Input = { readonly directory: Endpoint7_5Request["payload"]["directory"] }
export type Endpoint7_5Output = EffectValue<ReturnType<RawClient["experimental"]["worktreeReset"]>>
export type ExperimentalWorktreeResetOperation<E = never> = (
  input: Endpoint7_5Input,
) => Effect.Effect<Endpoint7_5Output, E>

export type Endpoint7_6Output = EffectValue<ReturnType<RawClient["experimental"]["resource"]>>
export type ExperimentalResourceOperation<E = never> = () => Effect.Effect<Endpoint7_6Output, E>

type Endpoint7_7Request = Parameters<RawClient["experimental"]["managedWorktreeCreate"]>[0]
export type Endpoint7_7Input = {
  readonly from: Endpoint7_7Request["payload"]["from"]
  readonly name?: Endpoint7_7Request["payload"]["name"]
  readonly into?: Endpoint7_7Request["payload"]["into"]
}
export type Endpoint7_7Output = EffectValue<ReturnType<RawClient["experimental"]["managedWorktreeCreate"]>>
export type ExperimentalManagedWorktreeCreateOperation<E = never> = (
  input: Endpoint7_7Input,
) => Effect.Effect<Endpoint7_7Output, E>

type Endpoint7_8Request = Parameters<RawClient["experimental"]["managedWorktreeRemove"]>[0]
export type Endpoint7_8Input = { readonly at: Endpoint7_8Request["payload"]["at"] }
export type Endpoint7_8Output = EffectValue<ReturnType<RawClient["experimental"]["managedWorktreeRemove"]>>
export type ExperimentalManagedWorktreeRemoveOperation<E = never> = (
  input: Endpoint7_8Input,
) => Effect.Effect<Endpoint7_8Output, E>

type Endpoint7_9Request = Parameters<RawClient["experimental"]["managedWorktreeLink"]>[0]
export type Endpoint7_9Input = {
  readonly at: Endpoint7_9Request["payload"]["at"]
  readonly to?: Endpoint7_9Request["payload"]["to"]
}
export type Endpoint7_9Output = EffectValue<ReturnType<RawClient["experimental"]["managedWorktreeLink"]>>
export type ExperimentalManagedWorktreeLinkOperation<E = never> = (
  input: Endpoint7_9Input,
) => Effect.Effect<Endpoint7_9Output, E>

type Endpoint7_10Request = Parameters<RawClient["experimental"]["managedWorktreeChildren"]>[0]
export type Endpoint7_10Input = { readonly of: Endpoint7_10Request["query"]["of"] }
export type Endpoint7_10Output = EffectValue<ReturnType<RawClient["experimental"]["managedWorktreeChildren"]>>
export type ExperimentalManagedWorktreeChildrenOperation<E = never> = (
  input: Endpoint7_10Input,
) => Effect.Effect<Endpoint7_10Output, E>

type Endpoint7_11Request = Parameters<RawClient["experimental"]["managedWorktreeAncestors"]>[0]
export type Endpoint7_11Input = { readonly of: Endpoint7_11Request["query"]["of"] }
export type Endpoint7_11Output = EffectValue<ReturnType<RawClient["experimental"]["managedWorktreeAncestors"]>>
export type ExperimentalManagedWorktreeAncestorsOperation<E = never> = (
  input: Endpoint7_11Input,
) => Effect.Effect<Endpoint7_11Output, E>

export type Endpoint7_12Output = EffectValue<ReturnType<RawClient["experimental"]["managedWorktreeList"]>>
export type ExperimentalManagedWorktreeListOperation<E = never> = () => Effect.Effect<Endpoint7_12Output, E>

export interface ExperimentalApi<E = never> {
  readonly toolIDs: ExperimentalToolIDsOperation<E>
  readonly tools: ExperimentalToolsOperation<E>
  readonly worktreeCreate: ExperimentalWorktreeCreateOperation<E>
  readonly worktree: ExperimentalWorktreeOperation<E>
  readonly worktreeRemove: ExperimentalWorktreeRemoveOperation<E>
  readonly worktreeReset: ExperimentalWorktreeResetOperation<E>
  readonly resource: ExperimentalResourceOperation<E>
  readonly managedWorktreeCreate: ExperimentalManagedWorktreeCreateOperation<E>
  readonly managedWorktreeRemove: ExperimentalManagedWorktreeRemoveOperation<E>
  readonly managedWorktreeLink: ExperimentalManagedWorktreeLinkOperation<E>
  readonly managedWorktreeChildren: ExperimentalManagedWorktreeChildrenOperation<E>
  readonly managedWorktreeAncestors: ExperimentalManagedWorktreeAncestorsOperation<E>
  readonly managedWorktreeList: ExperimentalManagedWorktreeListOperation<E>
}

type Endpoint8_0Request = Parameters<RawClient["file"]["findText"]>[0]
export type Endpoint8_0Input = { readonly pattern: Endpoint8_0Request["query"]["pattern"] }
export type Endpoint8_0Output = EffectValue<ReturnType<RawClient["file"]["findText"]>>
export type FileFindTextOperation<E = never> = (input: Endpoint8_0Input) => Effect.Effect<Endpoint8_0Output, E>

type Endpoint8_1Request = Parameters<RawClient["file"]["findFile"]>[0]
export type Endpoint8_1Input = {
  readonly query: Endpoint8_1Request["query"]["query"]
  readonly dirs?: Endpoint8_1Request["query"]["dirs"]
  readonly type?: Endpoint8_1Request["query"]["type"]
  readonly limit?: Endpoint8_1Request["query"]["limit"]
}
export type Endpoint8_1Output = EffectValue<ReturnType<RawClient["file"]["findFile"]>>
export type FileFindFileOperation<E = never> = (input: Endpoint8_1Input) => Effect.Effect<Endpoint8_1Output, E>

type Endpoint8_2Request = Parameters<RawClient["file"]["findSymbol"]>[0]
export type Endpoint8_2Input = { readonly query: Endpoint8_2Request["query"]["query"] }
export type Endpoint8_2Output = EffectValue<ReturnType<RawClient["file"]["findSymbol"]>>
export type FileFindSymbolOperation<E = never> = (input: Endpoint8_2Input) => Effect.Effect<Endpoint8_2Output, E>

type Endpoint8_3Request = Parameters<RawClient["file"]["list"]>[0]
export type Endpoint8_3Input = { readonly path: Endpoint8_3Request["query"]["path"] }
export type Endpoint8_3Output = EffectValue<ReturnType<RawClient["file"]["list"]>>
export type FileListOperation<E = never> = (input: Endpoint8_3Input) => Effect.Effect<Endpoint8_3Output, E>

type Endpoint8_4Request = Parameters<RawClient["file"]["content"]>[0]
export type Endpoint8_4Input = { readonly path: Endpoint8_4Request["query"]["path"] }
export type Endpoint8_4Output = EffectValue<ReturnType<RawClient["file"]["content"]>>
export type FileContentOperation<E = never> = (input: Endpoint8_4Input) => Effect.Effect<Endpoint8_4Output, E>

type Endpoint8_5Request = Parameters<RawClient["file"]["write"]>[0]
export type Endpoint8_5Input = {
  readonly path: Endpoint8_5Request["payload"]["path"]
  readonly content: Endpoint8_5Request["payload"]["content"]
}
export type Endpoint8_5Output = EffectValue<ReturnType<RawClient["file"]["write"]>>
export type FileWriteOperation<E = never> = (input: Endpoint8_5Input) => Effect.Effect<Endpoint8_5Output, E>

export type Endpoint8_6Output = EffectValue<ReturnType<RawClient["file"]["status"]>>
export type FileStatusOperation<E = never> = () => Effect.Effect<Endpoint8_6Output, E>

export interface FileApi<E = never> {
  readonly findText: FileFindTextOperation<E>
  readonly findFile: FileFindFileOperation<E>
  readonly findSymbol: FileFindSymbolOperation<E>
  readonly list: FileListOperation<E>
  readonly content: FileContentOperation<E>
  readonly write: FileWriteOperation<E>
  readonly status: FileStatusOperation<E>
}

export type Endpoint9_0Output = EffectValue<ReturnType<RawClient["global"]["health"]>>
export type GlobalHealthOperation<E = never> = () => Effect.Effect<Endpoint9_0Output, E>

export type Endpoint9_1Output = EffectValue<ReturnType<RawClient["global"]["dispose"]>>
export type GlobalDisposeOperation<E = never> = () => Effect.Effect<Endpoint9_1Output, E>

export interface GlobalApi<E = never> {
  readonly health: GlobalHealthOperation<E>
  readonly dispose: GlobalDisposeOperation<E>
}

export type Endpoint10_0Output = EffectValue<ReturnType<RawClient["mcp"]["status"]>>
export type McpStatusOperation<E = never> = () => Effect.Effect<Endpoint10_0Output, E>

type Endpoint10_1Request = Parameters<RawClient["mcp"]["add"]>[0]
export type Endpoint10_1Input = {
  readonly name: Endpoint10_1Request["payload"]["name"]
  readonly config: Endpoint10_1Request["payload"]["config"]
}
export type Endpoint10_1Output = EffectValue<ReturnType<RawClient["mcp"]["add"]>>
export type McpAddOperation<E = never> = (input: Endpoint10_1Input) => Effect.Effect<Endpoint10_1Output, E>

type Endpoint10_2Request = Parameters<RawClient["mcp"]["startAuth"]>[0]
export type Endpoint10_2Input = { readonly name: Endpoint10_2Request["params"]["name"] }
export type Endpoint10_2Output = EffectValue<ReturnType<RawClient["mcp"]["startAuth"]>>
export type McpStartAuthOperation<E = never> = (input: Endpoint10_2Input) => Effect.Effect<Endpoint10_2Output, E>

type Endpoint10_3Request = Parameters<RawClient["mcp"]["authCallback"]>[0]
export type Endpoint10_3Input = {
  readonly name: Endpoint10_3Request["params"]["name"]
  readonly code: Endpoint10_3Request["payload"]["code"]
}
export type Endpoint10_3Output = EffectValue<ReturnType<RawClient["mcp"]["authCallback"]>>
export type McpAuthCallbackOperation<E = never> = (input: Endpoint10_3Input) => Effect.Effect<Endpoint10_3Output, E>

type Endpoint10_4Request = Parameters<RawClient["mcp"]["authenticate"]>[0]
export type Endpoint10_4Input = { readonly name: Endpoint10_4Request["params"]["name"] }
export type Endpoint10_4Output = EffectValue<ReturnType<RawClient["mcp"]["authenticate"]>>
export type McpAuthenticateOperation<E = never> = (input: Endpoint10_4Input) => Effect.Effect<Endpoint10_4Output, E>

type Endpoint10_5Request = Parameters<RawClient["mcp"]["removeAuth"]>[0]
export type Endpoint10_5Input = { readonly name: Endpoint10_5Request["params"]["name"] }
export type Endpoint10_5Output = EffectValue<ReturnType<RawClient["mcp"]["removeAuth"]>>
export type McpRemoveAuthOperation<E = never> = (input: Endpoint10_5Input) => Effect.Effect<Endpoint10_5Output, E>

type Endpoint10_6Request = Parameters<RawClient["mcp"]["connect"]>[0]
export type Endpoint10_6Input = { readonly name: Endpoint10_6Request["params"]["name"] }
export type Endpoint10_6Output = EffectValue<ReturnType<RawClient["mcp"]["connect"]>>
export type McpConnectOperation<E = never> = (input: Endpoint10_6Input) => Effect.Effect<Endpoint10_6Output, E>

type Endpoint10_7Request = Parameters<RawClient["mcp"]["disconnect"]>[0]
export type Endpoint10_7Input = { readonly name: Endpoint10_7Request["params"]["name"] }
export type Endpoint10_7Output = EffectValue<ReturnType<RawClient["mcp"]["disconnect"]>>
export type McpDisconnectOperation<E = never> = (input: Endpoint10_7Input) => Effect.Effect<Endpoint10_7Output, E>

type Endpoint10_8Request = Parameters<RawClient["mcp"]["toggle"]>[0]
export type Endpoint10_8Input = {
  readonly name: Endpoint10_8Request["params"]["name"]
  readonly enabled: Endpoint10_8Request["payload"]["enabled"]
}
export type Endpoint10_8Output = EffectValue<ReturnType<RawClient["mcp"]["toggle"]>>
export type McpToggleOperation<E = never> = (input: Endpoint10_8Input) => Effect.Effect<Endpoint10_8Output, E>

export interface McpApi<E = never> {
  readonly status: McpStatusOperation<E>
  readonly add: McpAddOperation<E>
  readonly startAuth: McpStartAuthOperation<E>
  readonly authCallback: McpAuthCallbackOperation<E>
  readonly authenticate: McpAuthenticateOperation<E>
  readonly removeAuth: McpRemoveAuthOperation<E>
  readonly connect: McpConnectOperation<E>
  readonly disconnect: McpDisconnectOperation<E>
  readonly toggle: McpToggleOperation<E>
}

export type Endpoint11_0Output = EffectValue<ReturnType<RawClient["mission"]["list"]>>
export type MissionListOperation<E = never> = () => Effect.Effect<Endpoint11_0Output, E>

export type Endpoint11_1Output = EffectValue<ReturnType<RawClient["mission"]["templates"]>>
export type MissionTemplatesOperation<E = never> = () => Effect.Effect<Endpoint11_1Output, E>

type Endpoint11_2Request = Parameters<RawClient["mission"]["generate"]>[0]
export type Endpoint11_2Input = {
  readonly description: Endpoint11_2Request["payload"]["description"]
  readonly model?: Endpoint11_2Request["payload"]["model"]
  readonly agent?: Endpoint11_2Request["payload"]["agent"]
}
export type Endpoint11_2Output = EffectValue<ReturnType<RawClient["mission"]["generate"]>>
export type MissionGenerateOperation<E = never> = (input: Endpoint11_2Input) => Effect.Effect<Endpoint11_2Output, E>

type Endpoint11_3Request = Parameters<RawClient["mission"]["recentExecs"]>[0]
export type Endpoint11_3Input = { readonly limit?: Endpoint11_3Request["query"]["limit"] }
export type Endpoint11_3Output = EffectValue<ReturnType<RawClient["mission"]["recentExecs"]>>
export type MissionRecentExecsOperation<E = never> = (input?: Endpoint11_3Input) => Effect.Effect<Endpoint11_3Output, E>

type Endpoint11_4Request = Parameters<RawClient["mission"]["get"]>[0]
export type Endpoint11_4Input = { readonly id: Endpoint11_4Request["params"]["id"] }
export type Endpoint11_4Output = EffectValue<ReturnType<RawClient["mission"]["get"]>>
export type MissionGetOperation<E = never> = (input: Endpoint11_4Input) => Effect.Effect<Endpoint11_4Output, E>

type Endpoint11_5Request = Parameters<RawClient["mission"]["upsert"]>[0]
export type Endpoint11_5Input = { readonly payload: Endpoint11_5Request["payload"] }
export type Endpoint11_5Output = EffectValue<ReturnType<RawClient["mission"]["upsert"]>>
export type MissionUpsertOperation<E = never> = (input: Endpoint11_5Input) => Effect.Effect<Endpoint11_5Output, E>

type Endpoint11_6Request = Parameters<RawClient["mission"]["update"]>[0]
export type Endpoint11_6Input = {
  readonly id: Endpoint11_6Request["params"]["id"]
  readonly payload: Endpoint11_6Request["payload"]
}
export type Endpoint11_6Output = EffectValue<ReturnType<RawClient["mission"]["update"]>>
export type MissionUpdateOperation<E = never> = (input: Endpoint11_6Input) => Effect.Effect<Endpoint11_6Output, E>

type Endpoint11_7Request = Parameters<RawClient["mission"]["remove"]>[0]
export type Endpoint11_7Input = { readonly id: Endpoint11_7Request["params"]["id"] }
export type Endpoint11_7Output = EffectValue<ReturnType<RawClient["mission"]["remove"]>>
export type MissionRemoveOperation<E = never> = (input: Endpoint11_7Input) => Effect.Effect<Endpoint11_7Output, E>

type Endpoint11_8Request = Parameters<RawClient["mission"]["start"]>[0]
export type Endpoint11_8Input = { readonly id: Endpoint11_8Request["params"]["id"] }
export type Endpoint11_8Output = EffectValue<ReturnType<RawClient["mission"]["start"]>>
export type MissionStartOperation<E = never> = (input: Endpoint11_8Input) => Effect.Effect<Endpoint11_8Output, E>

type Endpoint11_9Request = Parameters<RawClient["mission"]["pause"]>[0]
export type Endpoint11_9Input = { readonly id: Endpoint11_9Request["params"]["id"] }
export type Endpoint11_9Output = EffectValue<ReturnType<RawClient["mission"]["pause"]>>
export type MissionPauseOperation<E = never> = (input: Endpoint11_9Input) => Effect.Effect<Endpoint11_9Output, E>

type Endpoint11_10Request = Parameters<RawClient["mission"]["cancel"]>[0]
export type Endpoint11_10Input = { readonly id: Endpoint11_10Request["params"]["id"] }
export type Endpoint11_10Output = EffectValue<ReturnType<RawClient["mission"]["cancel"]>>
export type MissionCancelOperation<E = never> = (input: Endpoint11_10Input) => Effect.Effect<Endpoint11_10Output, E>

type Endpoint11_11Request = Parameters<RawClient["mission"]["featureMutate"]>[0]
export type Endpoint11_11Input = {
  readonly id: Endpoint11_11Request["params"]["id"]
  readonly featureID: Endpoint11_11Request["params"]["featureID"]
  readonly status?: Endpoint11_11Request["payload"]["status"]
  readonly error?: Endpoint11_11Request["payload"]["error"]
  readonly appendDependsOn?: Endpoint11_11Request["payload"]["appendDependsOn"]
}
export type Endpoint11_11Output = EffectValue<ReturnType<RawClient["mission"]["featureMutate"]>>
export type MissionFeatureMutateOperation<E = never> = (
  input: Endpoint11_11Input,
) => Effect.Effect<Endpoint11_11Output, E>

type Endpoint11_12Request = Parameters<RawClient["mission"]["execs"]>[0]
export type Endpoint11_12Input = {
  readonly id: Endpoint11_12Request["params"]["id"]
  readonly limit?: Endpoint11_12Request["query"]["limit"]
}
export type Endpoint11_12Output = EffectValue<ReturnType<RawClient["mission"]["execs"]>>
export type MissionExecsOperation<E = never> = (input: Endpoint11_12Input) => Effect.Effect<Endpoint11_12Output, E>

export interface MissionApi<E = never> {
  readonly list: MissionListOperation<E>
  readonly templates: MissionTemplatesOperation<E>
  readonly generate: MissionGenerateOperation<E>
  readonly recentExecs: MissionRecentExecsOperation<E>
  readonly get: MissionGetOperation<E>
  readonly upsert: MissionUpsertOperation<E>
  readonly update: MissionUpdateOperation<E>
  readonly remove: MissionRemoveOperation<E>
  readonly start: MissionStartOperation<E>
  readonly pause: MissionPauseOperation<E>
  readonly cancel: MissionCancelOperation<E>
  readonly featureMutate: MissionFeatureMutateOperation<E>
  readonly execs: MissionExecsOperation<E>
}

export type Endpoint12_0Output = EffectValue<ReturnType<RawClient["project"]["list"]>>
export type ProjectListOperation<E = never> = () => Effect.Effect<Endpoint12_0Output, E>

export type Endpoint12_1Output = EffectValue<ReturnType<RawClient["project"]["current"]>>
export type ProjectCurrentOperation<E = never> = () => Effect.Effect<Endpoint12_1Output, E>

type Endpoint12_2Request = Parameters<RawClient["project"]["update"]>[0]
export type Endpoint12_2Input = {
  readonly projectID: Endpoint12_2Request["params"]["projectID"]
  readonly name?: Endpoint12_2Request["payload"]["name"]
  readonly icon?: Endpoint12_2Request["payload"]["icon"]
}
export type Endpoint12_2Output = EffectValue<ReturnType<RawClient["project"]["update"]>>
export type ProjectUpdateOperation<E = never> = (input: Endpoint12_2Input) => Effect.Effect<Endpoint12_2Output, E>

export interface ProjectApi<E = never> {
  readonly list: ProjectListOperation<E>
  readonly current: ProjectCurrentOperation<E>
  readonly update: ProjectUpdateOperation<E>
}

export type Endpoint13_0Output = EffectValue<ReturnType<RawClient["provider"]["list"]>>
export type ProviderListOperation<E = never> = () => Effect.Effect<Endpoint13_0Output, E>

export type Endpoint13_1Output = EffectValue<ReturnType<RawClient["provider"]["auth"]>>
export type ProviderAuthOperation<E = never> = () => Effect.Effect<Endpoint13_1Output, E>

type Endpoint13_2Request = Parameters<RawClient["provider"]["api"]>[0]
export type Endpoint13_2Input = {
  readonly providerID: Endpoint13_2Request["params"]["providerID"]
  readonly key: Endpoint13_2Request["payload"]["key"]
}
export type Endpoint13_2Output = EffectValue<ReturnType<RawClient["provider"]["api"]>>
export type ProviderApiOperation<E = never> = (input: Endpoint13_2Input) => Effect.Effect<Endpoint13_2Output, E>

type Endpoint13_3Request = Parameters<RawClient["provider"]["removeAuth"]>[0]
export type Endpoint13_3Input = { readonly providerID: Endpoint13_3Request["params"]["providerID"] }
export type Endpoint13_3Output = EffectValue<ReturnType<RawClient["provider"]["removeAuth"]>>
export type ProviderRemoveAuthOperation<E = never> = (input: Endpoint13_3Input) => Effect.Effect<Endpoint13_3Output, E>

type Endpoint13_4Request = Parameters<RawClient["provider"]["oauthAuthorize"]>[0]
export type Endpoint13_4Input = {
  readonly providerID: Endpoint13_4Request["params"]["providerID"]
  readonly method: Endpoint13_4Request["payload"]["method"]
}
export type Endpoint13_4Output = EffectValue<ReturnType<RawClient["provider"]["oauthAuthorize"]>>
export type ProviderOauthAuthorizeOperation<E = never> = (
  input: Endpoint13_4Input,
) => Effect.Effect<Endpoint13_4Output, E>

type Endpoint13_5Request = Parameters<RawClient["provider"]["oauthCallback"]>[0]
export type Endpoint13_5Input = {
  readonly providerID: Endpoint13_5Request["params"]["providerID"]
  readonly method: Endpoint13_5Request["payload"]["method"]
  readonly code?: Endpoint13_5Request["payload"]["code"]
}
export type Endpoint13_5Output = EffectValue<ReturnType<RawClient["provider"]["oauthCallback"]>>
export type ProviderOauthCallbackOperation<E = never> = (
  input: Endpoint13_5Input,
) => Effect.Effect<Endpoint13_5Output, E>

export interface ProviderApi<E = never> {
  readonly list: ProviderListOperation<E>
  readonly auth: ProviderAuthOperation<E>
  readonly api: ProviderApiOperation<E>
  readonly removeAuth: ProviderRemoveAuthOperation<E>
  readonly oauthAuthorize: ProviderOauthAuthorizeOperation<E>
  readonly oauthCallback: ProviderOauthCallbackOperation<E>
}

export type Endpoint14_0Output = EffectValue<ReturnType<RawClient["question"]["list"]>>
export type QuestionListOperation<E = never> = () => Effect.Effect<Endpoint14_0Output, E>

type Endpoint14_1Request = Parameters<RawClient["question"]["reply"]>[0]
export type Endpoint14_1Input = {
  readonly requestID: Endpoint14_1Request["params"]["requestID"]
  readonly answers: Endpoint14_1Request["payload"]["answers"]
}
export type Endpoint14_1Output = EffectValue<ReturnType<RawClient["question"]["reply"]>>
export type QuestionReplyOperation<E = never> = (input: Endpoint14_1Input) => Effect.Effect<Endpoint14_1Output, E>

type Endpoint14_2Request = Parameters<RawClient["question"]["reject"]>[0]
export type Endpoint14_2Input = { readonly requestID: Endpoint14_2Request["params"]["requestID"] }
export type Endpoint14_2Output = EffectValue<ReturnType<RawClient["question"]["reject"]>>
export type QuestionRejectOperation<E = never> = (input: Endpoint14_2Input) => Effect.Effect<Endpoint14_2Output, E>

export interface QuestionApi<E = never> {
  readonly list: QuestionListOperation<E>
  readonly reply: QuestionReplyOperation<E>
  readonly reject: QuestionRejectOperation<E>
}

export type Endpoint15_0Output = EffectValue<ReturnType<RawClient["permission"]["list"]>>
export type PermissionListOperation<E = never> = () => Effect.Effect<Endpoint15_0Output, E>

type Endpoint15_1Request = Parameters<RawClient["permission"]["reply"]>[0]
export type Endpoint15_1Input = {
  readonly requestID: Endpoint15_1Request["params"]["requestID"]
  readonly reply: Endpoint15_1Request["payload"]["reply"]
  readonly message?: Endpoint15_1Request["payload"]["message"]
}
export type Endpoint15_1Output = EffectValue<ReturnType<RawClient["permission"]["reply"]>>
export type PermissionReplyOperation<E = never> = (input: Endpoint15_1Input) => Effect.Effect<Endpoint15_1Output, E>

export interface PermissionApi<E = never> {
  readonly list: PermissionListOperation<E>
  readonly reply: PermissionReplyOperation<E>
}

export type Endpoint16_0Output = EffectValue<ReturnType<RawClient["pty"]["list"]>>
export type PtyListOperation<E = never> = () => Effect.Effect<Endpoint16_0Output, E>

type Endpoint16_1Request = Parameters<RawClient["pty"]["create"]>[0]
export type Endpoint16_1Input = {
  readonly command?: Endpoint16_1Request["payload"]["command"]
  readonly args?: Endpoint16_1Request["payload"]["args"]
  readonly cwd?: Endpoint16_1Request["payload"]["cwd"]
  readonly title?: Endpoint16_1Request["payload"]["title"]
  readonly env?: Endpoint16_1Request["payload"]["env"]
}
export type Endpoint16_1Output = EffectValue<ReturnType<RawClient["pty"]["create"]>>
export type PtyCreateOperation<E = never> = (input?: Endpoint16_1Input) => Effect.Effect<Endpoint16_1Output, E>

type Endpoint16_2Request = Parameters<RawClient["pty"]["get"]>[0]
export type Endpoint16_2Input = { readonly ptyID: Endpoint16_2Request["params"]["ptyID"] }
export type Endpoint16_2Output = EffectValue<ReturnType<RawClient["pty"]["get"]>>
export type PtyGetOperation<E = never> = (input: Endpoint16_2Input) => Effect.Effect<Endpoint16_2Output, E>

type Endpoint16_3Request = Parameters<RawClient["pty"]["update"]>[0]
export type Endpoint16_3Input = {
  readonly ptyID: Endpoint16_3Request["params"]["ptyID"]
  readonly title?: Endpoint16_3Request["payload"]["title"]
  readonly size?: Endpoint16_3Request["payload"]["size"]
}
export type Endpoint16_3Output = EffectValue<ReturnType<RawClient["pty"]["update"]>>
export type PtyUpdateOperation<E = never> = (input: Endpoint16_3Input) => Effect.Effect<Endpoint16_3Output, E>

type Endpoint16_4Request = Parameters<RawClient["pty"]["remove"]>[0]
export type Endpoint16_4Input = { readonly ptyID: Endpoint16_4Request["params"]["ptyID"] }
export type Endpoint16_4Output = EffectValue<ReturnType<RawClient["pty"]["remove"]>>
export type PtyRemoveOperation<E = never> = (input: Endpoint16_4Input) => Effect.Effect<Endpoint16_4Output, E>

export interface PtyApi<E = never> {
  readonly list: PtyListOperation<E>
  readonly create: PtyCreateOperation<E>
  readonly get: PtyGetOperation<E>
  readonly update: PtyUpdateOperation<E>
  readonly remove: PtyRemoveOperation<E>
}

export type Endpoint17_0Output = EffectValue<ReturnType<RawClient["loop"]["list"]>>
export type LoopListOperation<E = never> = () => Effect.Effect<Endpoint17_0Output, E>

export type Endpoint17_1Output = EffectValue<ReturnType<RawClient["loop"]["templates"]>>
export type LoopTemplatesOperation<E = never> = () => Effect.Effect<Endpoint17_1Output, E>

type Endpoint17_2Request = Parameters<RawClient["loop"]["generate"]>[0]
export type Endpoint17_2Input = {
  readonly description: Endpoint17_2Request["payload"]["description"]
  readonly model?: Endpoint17_2Request["payload"]["model"]
  readonly agent?: Endpoint17_2Request["payload"]["agent"]
}
export type Endpoint17_2Output = EffectValue<ReturnType<RawClient["loop"]["generate"]>>
export type LoopGenerateOperation<E = never> = (input: Endpoint17_2Input) => Effect.Effect<Endpoint17_2Output, E>

type Endpoint17_3Request = Parameters<RawClient["loop"]["recentRuns"]>[0]
export type Endpoint17_3Input = { readonly limit?: Endpoint17_3Request["query"]["limit"] }
export type Endpoint17_3Output = EffectValue<ReturnType<RawClient["loop"]["recentRuns"]>>
export type LoopRecentRunsOperation<E = never> = (input?: Endpoint17_3Input) => Effect.Effect<Endpoint17_3Output, E>

type Endpoint17_4Request = Parameters<RawClient["loop"]["get"]>[0]
export type Endpoint17_4Input = { readonly id: Endpoint17_4Request["params"]["id"] }
export type Endpoint17_4Output = EffectValue<ReturnType<RawClient["loop"]["get"]>>
export type LoopGetOperation<E = never> = (input: Endpoint17_4Input) => Effect.Effect<Endpoint17_4Output, E>

type Endpoint17_5Request = Parameters<RawClient["loop"]["upsert"]>[0]
export type Endpoint17_5Input = { readonly payload: Endpoint17_5Request["payload"] }
export type Endpoint17_5Output = EffectValue<ReturnType<RawClient["loop"]["upsert"]>>
export type LoopUpsertOperation<E = never> = (input: Endpoint17_5Input) => Effect.Effect<Endpoint17_5Output, E>

type Endpoint17_6Request = Parameters<RawClient["loop"]["update"]>[0]
export type Endpoint17_6Input = {
  readonly id: Endpoint17_6Request["params"]["id"]
  readonly payload: Endpoint17_6Request["payload"]
}
export type Endpoint17_6Output = EffectValue<ReturnType<RawClient["loop"]["update"]>>
export type LoopUpdateOperation<E = never> = (input: Endpoint17_6Input) => Effect.Effect<Endpoint17_6Output, E>

type Endpoint17_7Request = Parameters<RawClient["loop"]["remove"]>[0]
export type Endpoint17_7Input = { readonly id: Endpoint17_7Request["params"]["id"] }
export type Endpoint17_7Output = EffectValue<ReturnType<RawClient["loop"]["remove"]>>
export type LoopRemoveOperation<E = never> = (input: Endpoint17_7Input) => Effect.Effect<Endpoint17_7Output, E>

type Endpoint17_8Request = Parameters<RawClient["loop"]["toggle"]>[0]
export type Endpoint17_8Input = {
  readonly id: Endpoint17_8Request["params"]["id"]
  readonly enabled: Endpoint17_8Request["payload"]["enabled"]
}
export type Endpoint17_8Output = EffectValue<ReturnType<RawClient["loop"]["toggle"]>>
export type LoopToggleOperation<E = never> = (input: Endpoint17_8Input) => Effect.Effect<Endpoint17_8Output, E>

type Endpoint17_9Request = Parameters<RawClient["loop"]["run"]>[0]
export type Endpoint17_9Input = { readonly id: Endpoint17_9Request["params"]["id"] }
export type Endpoint17_9Output = EffectValue<ReturnType<RawClient["loop"]["run"]>>
export type LoopRunOperation<E = never> = (input: Endpoint17_9Input) => Effect.Effect<Endpoint17_9Output, E>

type Endpoint17_10Request = Parameters<RawClient["loop"]["abort"]>[0]
export type Endpoint17_10Input = { readonly id: Endpoint17_10Request["params"]["id"] }
export type Endpoint17_10Output = EffectValue<ReturnType<RawClient["loop"]["abort"]>>
export type LoopAbortOperation<E = never> = (input: Endpoint17_10Input) => Effect.Effect<Endpoint17_10Output, E>

type Endpoint17_11Request = Parameters<RawClient["loop"]["pause"]>[0]
export type Endpoint17_11Input = { readonly id: Endpoint17_11Request["params"]["id"] }
export type Endpoint17_11Output = EffectValue<ReturnType<RawClient["loop"]["pause"]>>
export type LoopPauseOperation<E = never> = (input: Endpoint17_11Input) => Effect.Effect<Endpoint17_11Output, E>

type Endpoint17_12Request = Parameters<RawClient["loop"]["resume"]>[0]
export type Endpoint17_12Input = { readonly id: Endpoint17_12Request["params"]["id"] }
export type Endpoint17_12Output = EffectValue<ReturnType<RawClient["loop"]["resume"]>>
export type LoopResumeOperation<E = never> = (input: Endpoint17_12Input) => Effect.Effect<Endpoint17_12Output, E>

type Endpoint17_13Request = Parameters<RawClient["loop"]["runs"]>[0]
export type Endpoint17_13Input = {
  readonly id: Endpoint17_13Request["params"]["id"]
  readonly limit?: Endpoint17_13Request["query"]["limit"]
}
export type Endpoint17_13Output = EffectValue<ReturnType<RawClient["loop"]["runs"]>>
export type LoopRunsOperation<E = never> = (input: Endpoint17_13Input) => Effect.Effect<Endpoint17_13Output, E>

export interface LoopApi<E = never> {
  readonly list: LoopListOperation<E>
  readonly templates: LoopTemplatesOperation<E>
  readonly generate: LoopGenerateOperation<E>
  readonly recentRuns: LoopRecentRunsOperation<E>
  readonly get: LoopGetOperation<E>
  readonly upsert: LoopUpsertOperation<E>
  readonly update: LoopUpdateOperation<E>
  readonly remove: LoopRemoveOperation<E>
  readonly toggle: LoopToggleOperation<E>
  readonly run: LoopRunOperation<E>
  readonly abort: LoopAbortOperation<E>
  readonly pause: LoopPauseOperation<E>
  readonly resume: LoopResumeOperation<E>
  readonly runs: LoopRunsOperation<E>
}

type Endpoint18_0Request = Parameters<RawClient["session"]["list"]>[0]
export type Endpoint18_0Input = {
  readonly directory?: Endpoint18_0Request["query"]["directory"]
  readonly roots?: Endpoint18_0Request["query"]["roots"]
  readonly start?: Endpoint18_0Request["query"]["start"]
  readonly search?: Endpoint18_0Request["query"]["search"]
  readonly limit?: Endpoint18_0Request["query"]["limit"]
}
export type Endpoint18_0Output = EffectValue<ReturnType<RawClient["session"]["list"]>>
export type SessionListOperation<E = never> = (input?: Endpoint18_0Input) => Effect.Effect<Endpoint18_0Output, E>

type Endpoint18_1Request = Parameters<RawClient["session"]["create"]>[0]
export type Endpoint18_1Input = {
  readonly parentID?: Endpoint18_1Request["payload"]["parentID"]
  readonly title?: Endpoint18_1Request["payload"]["title"]
  readonly permission?: Endpoint18_1Request["payload"]["permission"]
  readonly skills?: Endpoint18_1Request["payload"]["skills"]
  readonly github?: Endpoint18_1Request["payload"]["github"]
  readonly workspaceID?: Endpoint18_1Request["payload"]["workspaceID"]
}
export type Endpoint18_1Output = EffectValue<ReturnType<RawClient["session"]["create"]>>
export type SessionCreateOperation<E = never> = (input?: Endpoint18_1Input) => Effect.Effect<Endpoint18_1Output, E>

export type Endpoint18_2Output = EffectValue<ReturnType<RawClient["session"]["status"]>>
export type SessionStatusOperation<E = never> = () => Effect.Effect<Endpoint18_2Output, E>

type Endpoint18_3Request = Parameters<RawClient["session"]["get"]>[0]
export type Endpoint18_3Input = { readonly sessionID: Endpoint18_3Request["params"]["sessionID"] }
export type Endpoint18_3Output = EffectValue<ReturnType<RawClient["session"]["get"]>>
export type SessionGetOperation<E = never> = (input: Endpoint18_3Input) => Effect.Effect<Endpoint18_3Output, E>

type Endpoint18_4Request = Parameters<RawClient["session"]["remove"]>[0]
export type Endpoint18_4Input = { readonly sessionID: Endpoint18_4Request["params"]["sessionID"] }
export type Endpoint18_4Output = EffectValue<ReturnType<RawClient["session"]["remove"]>>
export type SessionRemoveOperation<E = never> = (input: Endpoint18_4Input) => Effect.Effect<Endpoint18_4Output, E>

type Endpoint18_5Request = Parameters<RawClient["session"]["update"]>[0]
export type Endpoint18_5Input = {
  readonly sessionID: Endpoint18_5Request["params"]["sessionID"]
  readonly title?: Endpoint18_5Request["payload"]["title"]
  readonly time?: Endpoint18_5Request["payload"]["time"]
}
export type Endpoint18_5Output = EffectValue<ReturnType<RawClient["session"]["update"]>>
export type SessionUpdateOperation<E = never> = (input: Endpoint18_5Input) => Effect.Effect<Endpoint18_5Output, E>

type Endpoint18_6Request = Parameters<RawClient["session"]["fork"]>[0]
export type Endpoint18_6Input = {
  readonly sessionID: Endpoint18_6Request["params"]["sessionID"]
  readonly messageID?: Endpoint18_6Request["payload"]["messageID"]
}
export type Endpoint18_6Output = EffectValue<ReturnType<RawClient["session"]["fork"]>>
export type SessionForkOperation<E = never> = (input: Endpoint18_6Input) => Effect.Effect<Endpoint18_6Output, E>

type Endpoint18_7Request = Parameters<RawClient["session"]["abort"]>[0]
export type Endpoint18_7Input = { readonly sessionID: Endpoint18_7Request["params"]["sessionID"] }
export type Endpoint18_7Output = EffectValue<ReturnType<RawClient["session"]["abort"]>>
export type SessionAbortOperation<E = never> = (input: Endpoint18_7Input) => Effect.Effect<Endpoint18_7Output, E>

type Endpoint18_8Request = Parameters<RawClient["session"]["revert"]>[0]
export type Endpoint18_8Input = {
  readonly sessionID: Endpoint18_8Request["params"]["sessionID"]
  readonly messageID: Endpoint18_8Request["payload"]["messageID"]
  readonly partID?: Endpoint18_8Request["payload"]["partID"]
}
export type Endpoint18_8Output = EffectValue<ReturnType<RawClient["session"]["revert"]>>
export type SessionRevertOperation<E = never> = (input: Endpoint18_8Input) => Effect.Effect<Endpoint18_8Output, E>

type Endpoint18_9Request = Parameters<RawClient["session"]["unrevert"]>[0]
export type Endpoint18_9Input = { readonly sessionID: Endpoint18_9Request["params"]["sessionID"] }
export type Endpoint18_9Output = EffectValue<ReturnType<RawClient["session"]["unrevert"]>>
export type SessionUnrevertOperation<E = never> = (input: Endpoint18_9Input) => Effect.Effect<Endpoint18_9Output, E>

type Endpoint18_10Request = Parameters<RawClient["session"]["share"]>[0]
export type Endpoint18_10Input = { readonly sessionID: Endpoint18_10Request["params"]["sessionID"] }
export type Endpoint18_10Output = EffectValue<ReturnType<RawClient["session"]["share"]>>
export type SessionShareOperation<E = never> = (input: Endpoint18_10Input) => Effect.Effect<Endpoint18_10Output, E>

type Endpoint18_11Request = Parameters<RawClient["session"]["unshare"]>[0]
export type Endpoint18_11Input = { readonly sessionID: Endpoint18_11Request["params"]["sessionID"] }
export type Endpoint18_11Output = EffectValue<ReturnType<RawClient["session"]["unshare"]>>
export type SessionUnshareOperation<E = never> = (input: Endpoint18_11Input) => Effect.Effect<Endpoint18_11Output, E>

type Endpoint18_12Request = Parameters<RawClient["session"]["summarize"]>[0]
export type Endpoint18_12Input = {
  readonly sessionID: Endpoint18_12Request["params"]["sessionID"]
  readonly providerID: Endpoint18_12Request["payload"]["providerID"]
  readonly modelID: Endpoint18_12Request["payload"]["modelID"]
  readonly auto?: Endpoint18_12Request["payload"]["auto"]
}
export type Endpoint18_12Output = EffectValue<ReturnType<RawClient["session"]["summarize"]>>
export type SessionSummarizeOperation<E = never> = (input: Endpoint18_12Input) => Effect.Effect<Endpoint18_12Output, E>

type Endpoint18_13Request = Parameters<RawClient["session"]["command"]>[0]
export type Endpoint18_13Input = {
  readonly sessionID: Endpoint18_13Request["params"]["sessionID"]
  readonly messageID?: Endpoint18_13Request["payload"]["messageID"]
  readonly agent?: Endpoint18_13Request["payload"]["agent"]
  readonly model?: Endpoint18_13Request["payload"]["model"]
  readonly arguments: Endpoint18_13Request["payload"]["arguments"]
  readonly command: Endpoint18_13Request["payload"]["command"]
  readonly variant?: Endpoint18_13Request["payload"]["variant"]
  readonly parts?: Endpoint18_13Request["payload"]["parts"]
}
export type Endpoint18_13Output = EffectValue<ReturnType<RawClient["session"]["command"]>>
export type SessionCommandOperation<E = never> = (input: Endpoint18_13Input) => Effect.Effect<Endpoint18_13Output, E>

type Endpoint18_14Request = Parameters<RawClient["session"]["shell"]>[0]
export type Endpoint18_14Input = {
  readonly sessionID: Endpoint18_14Request["params"]["sessionID"]
  readonly agent: Endpoint18_14Request["payload"]["agent"]
  readonly model?: Endpoint18_14Request["payload"]["model"]
  readonly command: Endpoint18_14Request["payload"]["command"]
}
export type Endpoint18_14Output = EffectValue<ReturnType<RawClient["session"]["shell"]>>
export type SessionShellOperation<E = never> = (input: Endpoint18_14Input) => Effect.Effect<Endpoint18_14Output, E>

type Endpoint18_15Request = Parameters<RawClient["session"]["permissionRespond"]>[0]
export type Endpoint18_15Input = {
  readonly sessionID: Endpoint18_15Request["params"]["sessionID"]
  readonly permissionID: Endpoint18_15Request["params"]["permissionID"]
  readonly response: Endpoint18_15Request["payload"]["response"]
}
export type Endpoint18_15Output = EffectValue<ReturnType<RawClient["session"]["permissionRespond"]>>
export type SessionPermissionRespondOperation<E = never> = (
  input: Endpoint18_15Input,
) => Effect.Effect<Endpoint18_15Output, E>

type Endpoint18_16Request = Parameters<RawClient["session"]["children"]>[0]
export type Endpoint18_16Input = { readonly sessionID: Endpoint18_16Request["params"]["sessionID"] }
export type Endpoint18_16Output = EffectValue<ReturnType<RawClient["session"]["children"]>>
export type SessionChildrenOperation<E = never> = (input: Endpoint18_16Input) => Effect.Effect<Endpoint18_16Output, E>

type Endpoint18_17Request = Parameters<RawClient["session"]["todo"]>[0]
export type Endpoint18_17Input = { readonly sessionID: Endpoint18_17Request["params"]["sessionID"] }
export type Endpoint18_17Output = EffectValue<ReturnType<RawClient["session"]["todo"]>>
export type SessionTodoOperation<E = never> = (input: Endpoint18_17Input) => Effect.Effect<Endpoint18_17Output, E>

type Endpoint18_18Request = Parameters<RawClient["session"]["diff"]>[0]
export type Endpoint18_18Input = {
  readonly sessionID: Endpoint18_18Request["params"]["sessionID"]
  readonly messageID?: Endpoint18_18Request["query"]["messageID"]
}
export type Endpoint18_18Output = EffectValue<ReturnType<RawClient["session"]["diff"]>>
export type SessionDiffOperation<E = never> = (input: Endpoint18_18Input) => Effect.Effect<Endpoint18_18Output, E>

type Endpoint18_19Request = Parameters<RawClient["session"]["messages"]>[0]
export type Endpoint18_19Input = {
  readonly sessionID: Endpoint18_19Request["params"]["sessionID"]
  readonly limit?: Endpoint18_19Request["query"]["limit"]
}
export type Endpoint18_19Output = EffectValue<ReturnType<RawClient["session"]["messages"]>>
export type SessionMessagesOperation<E = never> = (input: Endpoint18_19Input) => Effect.Effect<Endpoint18_19Output, E>

type Endpoint18_20Request = Parameters<RawClient["session"]["message"]>[0]
export type Endpoint18_20Input = {
  readonly sessionID: Endpoint18_20Request["params"]["sessionID"]
  readonly messageID: Endpoint18_20Request["params"]["messageID"]
}
export type Endpoint18_20Output = EffectValue<ReturnType<RawClient["session"]["message"]>>
export type SessionMessageOperation<E = never> = (input: Endpoint18_20Input) => Effect.Effect<Endpoint18_20Output, E>

type Endpoint18_21Request = Parameters<RawClient["session"]["messageRemove"]>[0]
export type Endpoint18_21Input = {
  readonly sessionID: Endpoint18_21Request["params"]["sessionID"]
  readonly messageID: Endpoint18_21Request["params"]["messageID"]
}
export type Endpoint18_21Output = EffectValue<ReturnType<RawClient["session"]["messageRemove"]>>
export type SessionMessageRemoveOperation<E = never> = (
  input: Endpoint18_21Input,
) => Effect.Effect<Endpoint18_21Output, E>

type Endpoint18_22Request = Parameters<RawClient["session"]["partRemove"]>[0]
export type Endpoint18_22Input = {
  readonly sessionID: Endpoint18_22Request["params"]["sessionID"]
  readonly messageID: Endpoint18_22Request["params"]["messageID"]
  readonly partID: Endpoint18_22Request["params"]["partID"]
}
export type Endpoint18_22Output = EffectValue<ReturnType<RawClient["session"]["partRemove"]>>
export type SessionPartRemoveOperation<E = never> = (input: Endpoint18_22Input) => Effect.Effect<Endpoint18_22Output, E>

type Endpoint18_23Request = Parameters<RawClient["session"]["partUpdate"]>[0]
export type Endpoint18_23Input = {
  readonly sessionID: Endpoint18_23Request["params"]["sessionID"]
  readonly messageID: Endpoint18_23Request["params"]["messageID"]
  readonly partID: Endpoint18_23Request["params"]["partID"]
  readonly payload: Endpoint18_23Request["payload"]
}
export type Endpoint18_23Output = EffectValue<ReturnType<RawClient["session"]["partUpdate"]>>
export type SessionPartUpdateOperation<E = never> = (input: Endpoint18_23Input) => Effect.Effect<Endpoint18_23Output, E>

type Endpoint18_24Request = Parameters<RawClient["session"]["v2Entries"]>[0]
export type Endpoint18_24Input = { readonly sessionID: Endpoint18_24Request["params"]["sessionID"] }
export type Endpoint18_24Output = EffectValue<ReturnType<RawClient["session"]["v2Entries"]>>
export type SessionV2EntriesOperation<E = never> = (input: Endpoint18_24Input) => Effect.Effect<Endpoint18_24Output, E>

type Endpoint18_25Request = Parameters<RawClient["session"]["v2State"]>[0]
export type Endpoint18_25Input = { readonly sessionID: Endpoint18_25Request["params"]["sessionID"] }
export type Endpoint18_25Output = EffectValue<ReturnType<RawClient["session"]["v2State"]>>
export type SessionV2StateOperation<E = never> = (input: Endpoint18_25Input) => Effect.Effect<Endpoint18_25Output, E>

type Endpoint18_26Request = Parameters<RawClient["session"]["v2Events"]>[0]
export type Endpoint18_26Input = { readonly sessionID: Endpoint18_26Request["params"]["sessionID"] }
export type Endpoint18_26Output = EffectValue<ReturnType<RawClient["session"]["v2Events"]>>
export type SessionV2EventsOperation<E = never> = (input: Endpoint18_26Input) => Effect.Effect<Endpoint18_26Output, E>

type Endpoint18_27Request = Parameters<RawClient["session"]["instructions"]>[0]
export type Endpoint18_27Input = { readonly sessionID: Endpoint18_27Request["params"]["sessionID"] }
export type Endpoint18_27Output = EffectValue<ReturnType<RawClient["session"]["instructions"]>>
export type SessionInstructionsOperation<E = never> = (
  input: Endpoint18_27Input,
) => Effect.Effect<Endpoint18_27Output, E>

type Endpoint18_28Request = Parameters<RawClient["session"]["contextBreakdown"]>[0]
export type Endpoint18_28Input = { readonly sessionID: Endpoint18_28Request["params"]["sessionID"] }
export type Endpoint18_28Output = EffectValue<ReturnType<RawClient["session"]["contextBreakdown"]>>
export type SessionContextBreakdownOperation<E = never> = (
  input: Endpoint18_28Input,
) => Effect.Effect<Endpoint18_28Output, E>

type Endpoint18_29Request = Parameters<RawClient["session"]["contextToggle"]>[0]
export type Endpoint18_29Input = {
  readonly sessionID: Endpoint18_29Request["params"]["sessionID"]
  readonly kind: Endpoint18_29Request["payload"]["kind"]
  readonly key: Endpoint18_29Request["payload"]["key"]
  readonly enabled: Endpoint18_29Request["payload"]["enabled"]
}
export type Endpoint18_29Output = EffectValue<ReturnType<RawClient["session"]["contextToggle"]>>
export type SessionContextToggleOperation<E = never> = (
  input: Endpoint18_29Input,
) => Effect.Effect<Endpoint18_29Output, E>

type Endpoint18_30Request = Parameters<RawClient["session"]["goal"]>[0]
export type Endpoint18_30Input = { readonly sessionID: Endpoint18_30Request["params"]["sessionID"] }
export type Endpoint18_30Output = EffectValue<ReturnType<RawClient["session"]["goal"]>>
export type SessionGoalOperation<E = never> = (input: Endpoint18_30Input) => Effect.Effect<Endpoint18_30Output, E>

type Endpoint18_31Request = Parameters<RawClient["session"]["background"]>[0]
export type Endpoint18_31Input = { readonly sessionID: Endpoint18_31Request["params"]["sessionID"] }
export type Endpoint18_31Output = EffectValue<ReturnType<RawClient["session"]["background"]>>
export type SessionBackgroundOperation<E = never> = (input: Endpoint18_31Input) => Effect.Effect<Endpoint18_31Output, E>

type Endpoint18_32Request = Parameters<RawClient["session"]["backgroundInspect"]>[0]
export type Endpoint18_32Input = {
  readonly sessionID: Endpoint18_32Request["params"]["sessionID"]
  readonly delegationID: Endpoint18_32Request["params"]["delegationID"]
}
export type Endpoint18_32Output = EffectValue<ReturnType<RawClient["session"]["backgroundInspect"]>>
export type SessionBackgroundInspectOperation<E = never> = (
  input: Endpoint18_32Input,
) => Effect.Effect<Endpoint18_32Output, E>

type Endpoint18_33Request = Parameters<RawClient["session"]["backgroundRead"]>[0]
export type Endpoint18_33Input = {
  readonly sessionID: Endpoint18_33Request["params"]["sessionID"]
  readonly delegationID: Endpoint18_33Request["params"]["delegationID"]
}
export type Endpoint18_33Output = EffectValue<ReturnType<RawClient["session"]["backgroundRead"]>>
export type SessionBackgroundReadOperation<E = never> = (
  input: Endpoint18_33Input,
) => Effect.Effect<Endpoint18_33Output, E>

type Endpoint18_34Request = Parameters<RawClient["session"]["backgroundCancel"]>[0]
export type Endpoint18_34Input = {
  readonly sessionID: Endpoint18_34Request["params"]["sessionID"]
  readonly delegationID: Endpoint18_34Request["params"]["delegationID"]
}
export type Endpoint18_34Output = EffectValue<ReturnType<RawClient["session"]["backgroundCancel"]>>
export type SessionBackgroundCancelOperation<E = never> = (
  input: Endpoint18_34Input,
) => Effect.Effect<Endpoint18_34Output, E>

type Endpoint18_35Request = Parameters<RawClient["session"]["monitor"]>[0]
export type Endpoint18_35Input = {
  readonly sessionID: Endpoint18_35Request["params"]["sessionID"]
  readonly monitorID: Endpoint18_35Request["params"]["monitorID"]
}
export type Endpoint18_35Output = EffectValue<ReturnType<RawClient["session"]["monitor"]>>
export type SessionMonitorOperation<E = never> = (input: Endpoint18_35Input) => Effect.Effect<Endpoint18_35Output, E>

type Endpoint18_36Request = Parameters<RawClient["session"]["monitorLog"]>[0]
export type Endpoint18_36Input = {
  readonly sessionID: Endpoint18_36Request["params"]["sessionID"]
  readonly monitorID: Endpoint18_36Request["params"]["monitorID"]
  readonly lines?: Endpoint18_36Request["query"]["lines"]
}
export type Endpoint18_36Output = EffectValue<ReturnType<RawClient["session"]["monitorLog"]>>
export type SessionMonitorLogOperation<E = never> = (input: Endpoint18_36Input) => Effect.Effect<Endpoint18_36Output, E>

type Endpoint18_37Request = Parameters<RawClient["session"]["monitorCancel"]>[0]
export type Endpoint18_37Input = {
  readonly sessionID: Endpoint18_37Request["params"]["sessionID"]
  readonly monitorID: Endpoint18_37Request["params"]["monitorID"]
}
export type Endpoint18_37Output = EffectValue<ReturnType<RawClient["session"]["monitorCancel"]>>
export type SessionMonitorCancelOperation<E = never> = (
  input: Endpoint18_37Input,
) => Effect.Effect<Endpoint18_37Output, E>

export interface SessionApi<E = never> {
  readonly list: SessionListOperation<E>
  readonly create: SessionCreateOperation<E>
  readonly status: SessionStatusOperation<E>
  readonly get: SessionGetOperation<E>
  readonly remove: SessionRemoveOperation<E>
  readonly update: SessionUpdateOperation<E>
  readonly fork: SessionForkOperation<E>
  readonly abort: SessionAbortOperation<E>
  readonly revert: SessionRevertOperation<E>
  readonly unrevert: SessionUnrevertOperation<E>
  readonly share: SessionShareOperation<E>
  readonly unshare: SessionUnshareOperation<E>
  readonly summarize: SessionSummarizeOperation<E>
  readonly command: SessionCommandOperation<E>
  readonly shell: SessionShellOperation<E>
  readonly permissionRespond: SessionPermissionRespondOperation<E>
  readonly children: SessionChildrenOperation<E>
  readonly todo: SessionTodoOperation<E>
  readonly diff: SessionDiffOperation<E>
  readonly messages: SessionMessagesOperation<E>
  readonly message: SessionMessageOperation<E>
  readonly messageRemove: SessionMessageRemoveOperation<E>
  readonly partRemove: SessionPartRemoveOperation<E>
  readonly partUpdate: SessionPartUpdateOperation<E>
  readonly v2Entries: SessionV2EntriesOperation<E>
  readonly v2State: SessionV2StateOperation<E>
  readonly v2Events: SessionV2EventsOperation<E>
  readonly instructions: SessionInstructionsOperation<E>
  readonly contextBreakdown: SessionContextBreakdownOperation<E>
  readonly contextToggle: SessionContextToggleOperation<E>
  readonly goal: SessionGoalOperation<E>
  readonly background: SessionBackgroundOperation<E>
  readonly backgroundInspect: SessionBackgroundInspectOperation<E>
  readonly backgroundRead: SessionBackgroundReadOperation<E>
  readonly backgroundCancel: SessionBackgroundCancelOperation<E>
  readonly monitor: SessionMonitorOperation<E>
  readonly monitorLog: SessionMonitorLogOperation<E>
  readonly monitorCancel: SessionMonitorCancelOperation<E>
}

type Endpoint19_0Request = Parameters<RawClient["sync"]["start"]>[0]
export type Endpoint19_0Input = {
  readonly url: Endpoint19_0Request["payload"]["url"]
  readonly token: Endpoint19_0Request["payload"]["token"]
  readonly projectID: Endpoint19_0Request["payload"]["projectID"]
}
export type Endpoint19_0Output = EffectValue<ReturnType<RawClient["sync"]["start"]>>
export type SyncStartOperation<E = never> = (input: Endpoint19_0Input) => Effect.Effect<Endpoint19_0Output, E>

type Endpoint19_1Request = Parameters<RawClient["sync"]["replay"]>[0]
export type Endpoint19_1Input = {
  readonly projectID: Endpoint19_1Request["payload"]["projectID"]
  readonly aggregate: Endpoint19_1Request["payload"]["aggregate"]
  readonly data: Endpoint19_1Request["payload"]["data"]
  readonly origin?: Endpoint19_1Request["payload"]["origin"]
}
export type Endpoint19_1Output = EffectValue<ReturnType<RawClient["sync"]["replay"]>>
export type SyncReplayOperation<E = never> = (input: Endpoint19_1Input) => Effect.Effect<Endpoint19_1Output, E>

type Endpoint19_2Request = Parameters<RawClient["sync"]["history"]>[0]
export type Endpoint19_2Input = {
  readonly projectID: Endpoint19_2Request["query"]["projectID"]
  readonly aggregate: Endpoint19_2Request["query"]["aggregate"]
  readonly since?: Endpoint19_2Request["query"]["since"]
  readonly limit?: Endpoint19_2Request["query"]["limit"]
}
export type Endpoint19_2Output = EffectValue<ReturnType<RawClient["sync"]["history"]>>
export type SyncHistoryOperation<E = never> = (input: Endpoint19_2Input) => Effect.Effect<Endpoint19_2Output, E>

type Endpoint19_3Request = Parameters<RawClient["sync"]["snapshot"]>[0]
export type Endpoint19_3Input = {
  readonly projectID: Endpoint19_3Request["query"]["projectID"]
  readonly aggregate: Endpoint19_3Request["query"]["aggregate"]
}
export type Endpoint19_3Output = EffectValue<ReturnType<RawClient["sync"]["snapshot"]>>
export type SyncSnapshotOperation<E = never> = (input: Endpoint19_3Input) => Effect.Effect<Endpoint19_3Output, E>

export interface SyncApi<E = never> {
  readonly start: SyncStartOperation<E>
  readonly replay: SyncReplayOperation<E>
  readonly history: SyncHistoryOperation<E>
  readonly snapshot: SyncSnapshotOperation<E>
}

type Endpoint20_0Request = Parameters<RawClient["tui"]["appendPrompt"]>[0]
export type Endpoint20_0Input = { readonly payload: Endpoint20_0Request["payload"] }
export type Endpoint20_0Output = EffectValue<ReturnType<RawClient["tui"]["appendPrompt"]>>
export type TuiAppendPromptOperation<E = never> = (input: Endpoint20_0Input) => Effect.Effect<Endpoint20_0Output, E>

export type Endpoint20_1Output = EffectValue<ReturnType<RawClient["tui"]["openHelp"]>>
export type TuiOpenHelpOperation<E = never> = () => Effect.Effect<Endpoint20_1Output, E>

export type Endpoint20_2Output = EffectValue<ReturnType<RawClient["tui"]["openSessions"]>>
export type TuiOpenSessionsOperation<E = never> = () => Effect.Effect<Endpoint20_2Output, E>

export type Endpoint20_3Output = EffectValue<ReturnType<RawClient["tui"]["openThemes"]>>
export type TuiOpenThemesOperation<E = never> = () => Effect.Effect<Endpoint20_3Output, E>

export type Endpoint20_4Output = EffectValue<ReturnType<RawClient["tui"]["openModels"]>>
export type TuiOpenModelsOperation<E = never> = () => Effect.Effect<Endpoint20_4Output, E>

export type Endpoint20_5Output = EffectValue<ReturnType<RawClient["tui"]["submitPrompt"]>>
export type TuiSubmitPromptOperation<E = never> = () => Effect.Effect<Endpoint20_5Output, E>

export type Endpoint20_6Output = EffectValue<ReturnType<RawClient["tui"]["clearPrompt"]>>
export type TuiClearPromptOperation<E = never> = () => Effect.Effect<Endpoint20_6Output, E>

type Endpoint20_7Request = Parameters<RawClient["tui"]["executeCommand"]>[0]
export type Endpoint20_7Input = { readonly payload: Endpoint20_7Request["payload"] }
export type Endpoint20_7Output = EffectValue<ReturnType<RawClient["tui"]["executeCommand"]>>
export type TuiExecuteCommandOperation<E = never> = (input: Endpoint20_7Input) => Effect.Effect<Endpoint20_7Output, E>

type Endpoint20_8Request = Parameters<RawClient["tui"]["showToast"]>[0]
export type Endpoint20_8Input = { readonly payload: Endpoint20_8Request["payload"] }
export type Endpoint20_8Output = EffectValue<ReturnType<RawClient["tui"]["showToast"]>>
export type TuiShowToastOperation<E = never> = (input: Endpoint20_8Input) => Effect.Effect<Endpoint20_8Output, E>

type Endpoint20_9Request = Parameters<RawClient["tui"]["publish"]>[0]
export type Endpoint20_9Input = { readonly payload: Endpoint20_9Request["payload"] }
export type Endpoint20_9Output = EffectValue<ReturnType<RawClient["tui"]["publish"]>>
export type TuiPublishOperation<E = never> = (input: Endpoint20_9Input) => Effect.Effect<Endpoint20_9Output, E>

type Endpoint20_10Request = Parameters<RawClient["tui"]["selectSession"]>[0]
export type Endpoint20_10Input = { readonly payload: Endpoint20_10Request["payload"] }
export type Endpoint20_10Output = EffectValue<ReturnType<RawClient["tui"]["selectSession"]>>
export type TuiSelectSessionOperation<E = never> = (input: Endpoint20_10Input) => Effect.Effect<Endpoint20_10Output, E>

export type Endpoint20_11Output = EffectValue<ReturnType<RawClient["tui"]["controlNext"]>>
export type TuiControlNextOperation<E = never> = () => Effect.Effect<Endpoint20_11Output, E>

type Endpoint20_12Request = Parameters<RawClient["tui"]["controlResponse"]>[0]
export type Endpoint20_12Input = { readonly payload: Endpoint20_12Request["payload"] }
export type Endpoint20_12Output = EffectValue<ReturnType<RawClient["tui"]["controlResponse"]>>
export type TuiControlResponseOperation<E = never> = (
  input: Endpoint20_12Input,
) => Effect.Effect<Endpoint20_12Output, E>

export interface TuiApi<E = never> {
  readonly appendPrompt: TuiAppendPromptOperation<E>
  readonly openHelp: TuiOpenHelpOperation<E>
  readonly openSessions: TuiOpenSessionsOperation<E>
  readonly openThemes: TuiOpenThemesOperation<E>
  readonly openModels: TuiOpenModelsOperation<E>
  readonly submitPrompt: TuiSubmitPromptOperation<E>
  readonly clearPrompt: TuiClearPromptOperation<E>
  readonly executeCommand: TuiExecuteCommandOperation<E>
  readonly showToast: TuiShowToastOperation<E>
  readonly publish: TuiPublishOperation<E>
  readonly selectSession: TuiSelectSessionOperation<E>
  readonly controlNext: TuiControlNextOperation<E>
  readonly controlResponse: TuiControlResponseOperation<E>
}

export type Endpoint21_0Output = EffectValue<ReturnType<RawClient["workspace"]["adaptors"]>>
export type WorkspaceAdaptorsOperation<E = never> = () => Effect.Effect<Endpoint21_0Output, E>

export type Endpoint21_1Output = EffectValue<ReturnType<RawClient["workspace"]["syncList"]>>
export type WorkspaceSyncListOperation<E = never> = () => Effect.Effect<Endpoint21_1Output, E>

export type Endpoint21_2Output = EffectValue<ReturnType<RawClient["workspace"]["status"]>>
export type WorkspaceStatusOperation<E = never> = () => Effect.Effect<Endpoint21_2Output, E>

type Endpoint21_3Request = Parameters<RawClient["workspace"]["create"]>[0]
export type Endpoint21_3Input = {
  readonly id: Endpoint21_3Request["params"]["id"]
  readonly branch: Endpoint21_3Request["payload"]["branch"]
  readonly config: Endpoint21_3Request["payload"]["config"]
}
export type Endpoint21_3Output = EffectValue<ReturnType<RawClient["workspace"]["create"]>>
export type WorkspaceCreateOperation<E = never> = (input: Endpoint21_3Input) => Effect.Effect<Endpoint21_3Output, E>

export type Endpoint21_4Output = EffectValue<ReturnType<RawClient["workspace"]["list"]>>
export type WorkspaceListOperation<E = never> = () => Effect.Effect<Endpoint21_4Output, E>

type Endpoint21_5Request = Parameters<RawClient["workspace"]["remove"]>[0]
export type Endpoint21_5Input = { readonly id: Endpoint21_5Request["params"]["id"] }
export type Endpoint21_5Output = EffectValue<ReturnType<RawClient["workspace"]["remove"]>>
export type WorkspaceRemoveOperation<E = never> = (input: Endpoint21_5Input) => Effect.Effect<Endpoint21_5Output, E>

type Endpoint21_6Request = Parameters<RawClient["workspace"]["restore"]>[0]
export type Endpoint21_6Input = {
  readonly id: Endpoint21_6Request["params"]["id"]
  readonly timeoutMs?: Endpoint21_6Request["query"]["timeoutMs"]
}
export type Endpoint21_6Output = EffectValue<ReturnType<RawClient["workspace"]["restore"]>>
export type WorkspaceRestoreOperation<E = never> = (input: Endpoint21_6Input) => Effect.Effect<Endpoint21_6Output, E>

type Endpoint21_7Request = Parameters<RawClient["workspace"]["sessionRestore"]>[0]
export type Endpoint21_7Input = {
  readonly id: Endpoint21_7Request["params"]["id"]
  readonly sessionID: Endpoint21_7Request["params"]["sessionID"]
  readonly timeoutMs?: Endpoint21_7Request["query"]["timeoutMs"]
}
export type Endpoint21_7Output = EffectValue<ReturnType<RawClient["workspace"]["sessionRestore"]>>
export type WorkspaceSessionRestoreOperation<E = never> = (
  input: Endpoint21_7Input,
) => Effect.Effect<Endpoint21_7Output, E>

type Endpoint21_8Request = Parameters<RawClient["workspace"]["warp"]>[0]
export type Endpoint21_8Input = {
  readonly id: Endpoint21_8Request["payload"]["id"]
  readonly sessionID: Endpoint21_8Request["payload"]["sessionID"]
  readonly copyChanges?: Endpoint21_8Request["payload"]["copyChanges"]
  readonly timeoutMs?: Endpoint21_8Request["payload"]["timeoutMs"]
}
export type Endpoint21_8Output = EffectValue<ReturnType<RawClient["workspace"]["warp"]>>
export type WorkspaceWarpOperation<E = never> = (input: Endpoint21_8Input) => Effect.Effect<Endpoint21_8Output, E>

export interface WorkspaceApi<E = never> {
  readonly adaptors: WorkspaceAdaptorsOperation<E>
  readonly syncList: WorkspaceSyncListOperation<E>
  readonly status: WorkspaceStatusOperation<E>
  readonly create: WorkspaceCreateOperation<E>
  readonly list: WorkspaceListOperation<E>
  readonly remove: WorkspaceRemoveOperation<E>
  readonly restore: WorkspaceRestoreOperation<E>
  readonly sessionRestore: WorkspaceSessionRestoreOperation<E>
  readonly warp: WorkspaceWarpOperation<E>
}

export interface AppApi<E = never> {
  readonly "top-level": TopLevelApi<E>
  readonly analytics: AnalyticsApi<E>
  readonly app: AppApi<E>
  readonly brain: BrainApi<E>
  readonly config: ConfigApi<E>
  readonly connectors: ConnectorsApi<E>
  readonly doctor: DoctorApi<E>
  readonly experimental: ExperimentalApi<E>
  readonly file: FileApi<E>
  readonly global: GlobalApi<E>
  readonly mcp: McpApi<E>
  readonly mission: MissionApi<E>
  readonly project: ProjectApi<E>
  readonly provider: ProviderApi<E>
  readonly question: QuestionApi<E>
  readonly permission: PermissionApi<E>
  readonly pty: PtyApi<E>
  readonly loop: LoopApi<E>
  readonly session: SessionApi<E>
  readonly sync: SyncApi<E>
  readonly tui: TuiApi<E>
  readonly workspace: WorkspaceApi<E>
}
