/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{js,jsx,ts,tsx}", "./components/**/*.{js,jsx,ts,tsx}"],
  safelist: ["dark"],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        background: "rgb(var(--color-background) / <alpha-value>)",
        surface: "rgb(var(--color-surface) / <alpha-value>)",
        panel: "rgb(var(--color-panel) / <alpha-value>)",
        border: "rgb(var(--color-border) / <alpha-value>)",
        accent: "rgb(var(--color-accent) / <alpha-value>)",
        "accent-strong": "rgb(var(--color-accent-strong) / <alpha-value>)",
        "accent-light": "rgb(var(--color-accent-light) / <alpha-value>)",
        "accent-glow": "rgb(var(--color-accent-glow) / <alpha-value>)",
        "accent-subtle": "rgb(var(--color-accent-subtle) / <alpha-value>)",
        muted: "rgb(var(--color-muted) / <alpha-value>)",
        ink: "rgb(var(--color-ink) / <alpha-value>)",
        soft: "rgb(var(--color-soft) / <alpha-value>)",
        "user-bubble": "rgb(var(--color-user-bubble) / <alpha-value>)",
        "assistant-bubble": "rgb(var(--color-assistant-bubble) / <alpha-value>)",
        success: "rgb(var(--color-success) / <alpha-value>)",
        danger: "rgb(var(--color-danger) / <alpha-value>)",
        warning: "rgb(var(--color-warning) / <alpha-value>)",
        info: "rgb(var(--color-info) / <alpha-value>)",
        // Glass material system
        "glass-shell": "rgb(var(--color-glass-shell) / <alpha-value>)",
        "glass-shell-strong": "rgb(var(--color-glass-shell-strong) / <alpha-value>)",
        "glass-panel": "rgb(var(--color-glass-panel) / <alpha-value>)",
        "glass-border": "rgb(var(--color-glass-border) / <alpha-value>)",
        "glass-shadow": "rgb(var(--color-glass-shadow) / <alpha-value>)",
        "glass-glow": "rgb(var(--color-glass-glow) / <alpha-value>)",
        overlay: "rgb(var(--color-overlay) / <alpha-value>)",
        "focus-ring": "rgb(var(--color-focus-ring) / <alpha-value>)",
      },
      borderRadius: {
        xs: "6px",
        sm: "8px",
        DEFAULT: "12px",
        md: "14px",
        lg: "16px",
        xl: "20px",
        "2xl": "24px",
        "3xl": "30px",
        "4xl": "34px",
        pill: "9999px",
      },
      boxShadow: {
        "space-sm": "0 10px 18px rgba(2, 6, 23, 0.16)",
        "space-md": "0 18px 30px rgba(2, 6, 23, 0.22)",
        "glow-accent": "0 0 0 1px rgba(56, 189, 248, 0.14), 0 16px 30px rgba(56, 189, 248, 0.12)",
        "glow-accent-strong": "0 0 0 1px rgba(59, 130, 246, 0.25), 0 20px 40px rgba(59, 130, 246, 0.20)",
        glass: "0 2px 8px rgba(0, 0, 0, 0.06), 0 0 0 1px rgba(255, 255, 255, 0.18)",
        "glass-strong": "0 8px 32px rgba(0, 0, 0, 0.20), 0 0 0 1px rgba(255, 255, 255, 0.25)",
        soft: "0 4px 24px rgba(0, 0, 0, 0.08), 0 1px 4px rgba(0, 0, 0, 0.04)",
        float: "0 8px 32px rgba(0, 0, 0, 0.12), 0 2px 8px rgba(0, 0, 0, 0.08)",
        "float-strong": "0 16px 48px rgba(0, 0, 0, 0.25), 0 4px 12px rgba(0, 0, 0, 0.12)",
        "focus-ring": "0 0 0 3px rgba(14, 165, 233, 0.35)",
        "inner-sm": "inset 0 1px 3px rgba(0, 0, 0, 0.08)",
      },
      // iOS 26 Liquid Glass easing + existing Emil's
      transitionTimingFunction: {
        "out-strong": "cubic-bezier(0.23, 1, 0.32, 1)",
        "in-out-strong": "cubic-bezier(0.77, 0, 0.175, 1)",
        drawer: "cubic-bezier(0.32, 0.72, 0, 1)",
        spring: "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "spring-gentle": "cubic-bezier(0.175, 0.885, 0.32, 1.275)",
        bounce: "cubic-bezier(0.68, -0.55, 0.265, 1.55)",
        snappy: "cubic-bezier(0.2, 0, 0, 1)",
        // iOS 26 Liquid Glass
        liquid: "cubic-bezier(0.25, 0.1, 0.25, 1)",
        "liquid-bounce": "cubic-bezier(0.34, 1.56, 0.64, 1)",
        "liquid-snap": "cubic-bezier(0.2, 0, 0, 1)",
        "ios-large-title": "cubic-bezier(0.3, 0, 0.7, 1)",
      },
      transitionDuration: {
        instant: "50ms",
        quick: "100ms",
        fast: "150ms",
        ui: "200ms",
        enter: "250ms",
        modal: "300ms",
        slow: "500ms",
        skeleton: "1200ms",
        // iOS 26 Liquid Glass
        liquid: "280ms",
        "liquid-fast": "180ms",
        "liquid-slow": "400ms",
      },
      transitionDelay: {
        0: "0ms",
        stagger1: "30ms",
        stagger2: "60ms",
        stagger3: "90ms",
        stagger4: "120ms",
        stagger5: "150ms",
      },
      scale: {
        97: "0.97",
        98: "0.98",
        99: "0.99",
        101: "1.01",
        102: "1.02",
        103: "1.03",
      },
      opacity: {
        hover: "0.88",
        "button-pressed": "0.84",
        "button-disabled": "0.58",
        scrim: "0.45",
        glass: "0.72",
      },
      backdropBlur: {
        glass: "16px",
        "glass-strong": "24px",
        "glass-liquid": "32px",
      },
      blur: {
        subtle: "2px",
        soft: "4px",
        glass: "16px",
        "glass-strong": "24px",
      },
      letterSpacing: {
        display: "-0.03em",
        heading: "-0.02em",
        body: "-0.01em",
        normal: "0em",
        caps: "0.08em",
        wide: "0.12em",
      },
      lineHeight: {
        display: "1.1",
        heading: "1.25",
        snug: "1.375",
        body: "1.5",
        relaxed: "1.625",
      },
      fontFamily: {
        system: ["-apple-system", "BlinkMacSystemFont", "sans-serif"],
        mono: ["Menlo", "Monaco", "Courier New", "monospace"],
      },
      spacing: {
        18: "4.5rem",
        22: "5.5rem",
      },
      // iOS 26 animation keyframes
      animation: {
        shimmer: "shimmer 1200ms ease-in-out infinite",
        "pulse-slow": "pulse 2000ms ease-in-out infinite",
        "bounce-in": "bounceIn 300ms cubic-bezier(0.34, 1.56, 0.64, 1)",
        "fade-in": "fadeIn 200ms ease-out",
        "slide-up": "slideUp 250ms cubic-bezier(0.23, 1, 0.32, 1)",
        "scale-in": "scaleIn 200ms cubic-bezier(0.2, 0, 0, 1)",
      },
      keyframes: {
        shimmer: {
          "0%, 100%": { opacity: "0.35" },
          "50%": { opacity: "0.75" },
        },
        bounceIn: {
          "0%": { transform: "scale(0.9)", opacity: "0" },
          "70%": { transform: "scale(1.05)" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        slideUp: {
          "0%": { transform: "translateY(10px)", opacity: "0" },
          "100%": { transform: "translateY(0)", opacity: "1" },
        },
        scaleIn: {
          "0%": { transform: "scale(0.95)", opacity: "0" },
          "100%": { transform: "scale(1)", opacity: "1" },
        },
      },
    },
  },
  plugins: [],
}
