import { inviteUrl, lookupBotUser } from "./invite"

function ask(question: string): string {
  const answer = prompt(question)
  return (answer ?? "").trim()
}

function quoteEnv(value: string): string {
  if (/^[A-Za-z0-9_./:=+-]*$/.test(value)) return value
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"')}"`
}

console.log(`
=== Setup bot Discord nikcli ===

Percorso consigliato: apri la TUI nikcli e lancia /discord.
Questo wizard è il fallback da riga di comando.
`)

let token = ""
for (let attempt = 0; attempt < 3; attempt++) {
  token = ask("Incolla il token del bot Discord:")
  if (!token) {
    console.error("Serve un token. Lo trovi in Discord Developer Portal → Bot → Reset Token.")
    continue
  }
  try {
    const user = await lookupBotUser(token)
    const nikcliUrl = ask("URL del server nikcli (Invio per avviare un server locale):")
    const openrouter = ask("Chiave OpenRouter per i messaggi vocali (opzionale):")

    const lines = [
      "# Generated by bun run setup",
      `DISCORD_BOT_TOKEN=${quoteEnv(token)}`,
      `DISCORD_CLIENT_ID=${quoteEnv(user.id)}`,
    ]
    if (nikcliUrl) lines.push(`NIKCLI_URL=${quoteEnv(nikcliUrl)}`)
    else lines.push("# NIKCLI_URL=")
    if (openrouter) lines.push(`OPENROUTER_API_KEY=${quoteEnv(openrouter)}`)
    else lines.push("# OPENROUTER_API_KEY=")
    lines.push(
      "",
      "# Optional",
      "# DISCORD_ALLOWED_CHANNELS=",
      "# DISCORD_ADMIN_USERS=",
      "# DISCORD_DEFAULT_TOOLS=",
      "# HEALTH_PORT=3000",
    )

    const envPath = `${process.cwd()}/.env`
    await Bun.write(envPath, `${lines.join("\n")}\n`)

    const url = inviteUrl(user.id)
    console.log(`
Bot: ${user.username} (${user.id})
File scritto: ${envPath}

1. Abilita Message Content Intent
   Discord Developer Portal → la tua app → Bot → Privileged Gateway Intents

2. Invita il bot nel server:
   ${url}

3. Avvia: bun run dev
`)
    process.exit(0)
  } catch (err) {
    const message = err instanceof Error ? err.message : String(err)
    if (message === "Invalid Discord bot token") {
      console.error("Token non valido. Controlla di aver copiato il Bot Token (non il public key).")
      continue
    }
    console.error(message)
    process.exit(1)
  }
}

console.error("Setup annullato: token mancante o non valido.")
process.exit(1)
