import type { useLanguage } from "@tui/context/language"

type Language = ReturnType<typeof useLanguage>

export function sessionCommandLabels(lang: Language) {
  return {
    category: lang.t("session.category"),
    backgroundSubtask: lang.t("session.cmd.backgroundSubtask"),
    backgroundAgents: lang.t("session.cmd.backgroundAgents"),
    share: lang.t("session.cmd.share"),
    copyShareLink: lang.t("session.cmd.copyShareLink"),
    rename: lang.t("session.cmd.rename"),
    jumpToMessage: lang.t("session.cmd.jumpToMessage"),
    forkFromMessage: lang.t("session.cmd.forkFromMessage"),
    compact: lang.t("session.cmd.compact"),
    unshare: lang.t("session.cmd.unshare"),
    undo: lang.t("session.cmd.undo"),
    redo: lang.t("session.cmd.redo"),
    hideSidebar: lang.t("session.cmd.hideSidebar"),
    showSidebar: lang.t("session.cmd.showSidebar"),
    toggleConceal: lang.t("session.cmd.toggleConceal"),
    hideTimestamps: lang.t("session.cmd.hideTimestamps"),
    showTimestamps: lang.t("session.cmd.showTimestamps"),
    hideThinking: lang.t("session.cmd.hideThinking"),
    showThinking: lang.t("session.cmd.showThinking"),
    toggleDiffWrap: lang.t("session.cmd.toggleDiffWrap"),
    hideToolDetails: lang.t("session.cmd.hideToolDetails"),
    showToolDetails: lang.t("session.cmd.showToolDetails"),
    toggleScrollbar: lang.t("session.cmd.toggleScrollbar"),
    disableAnimations: lang.t("session.cmd.disableAnimations"),
    enableAnimations: lang.t("session.cmd.enableAnimations"),
    pageUp: lang.t("session.cmd.pageUp"),
    pageDown: lang.t("session.cmd.pageDown"),
    lineUp: lang.t("session.cmd.lineUp"),
    lineDown: lang.t("session.cmd.lineDown"),
    halfPageUp: lang.t("session.cmd.halfPageUp"),
    halfPageDown: lang.t("session.cmd.halfPageDown"),
    firstMessage: lang.t("session.cmd.firstMessage"),
    lastMessage: lang.t("session.cmd.lastMessage"),
    lastUserMessage: lang.t("session.cmd.lastUserMessage"),
    nextMessage: lang.t("session.cmd.nextMessage"),
    prevMessage: lang.t("session.cmd.prevMessage"),
    copyLastAssistant: lang.t("session.cmd.copyLastAssistant"),
    copyTranscript: lang.t("session.cmd.copyTranscript"),
    exportTranscript: lang.t("session.cmd.exportTranscript"),
    nextChild: lang.t("session.cmd.nextChild"),
    prevChild: lang.t("session.cmd.prevChild"),
    parent: lang.t("session.cmd.parent"),
    closeSubagent: lang.t("session.cmd.closeSubagent"),
  } as const
}
