import { Effect } from "effect"
import { HttpServerRequest, HttpServerResponse } from "effect/unstable/http"
import { HttpApiBuilder } from "effect/unstable/httpapi"
import { dispatchMobileRequest } from "../mobile/dispatcher"
import { MobileHttpApi } from "./mobile"

function forward({ request }: { readonly request: HttpServerRequest.HttpServerRequest }) {
  return Effect.promise(async () => {
    // SAFETY: `source` is typed `unknown` because Effect supports several
    // server adapters. nikcli only ever serves this router through
    // `Server.fetch`, i.e. the web-standard adapter, where `source` is the
    // incoming `Request` that adapter was handed.
    const source = request.source as Request
    return (await dispatchMobileRequest(source)) ?? new Response("Not Found", { status: 404 })
  }).pipe(Effect.map(HttpServerResponse.fromWeb))
}

export const MobileHandlersLive = HttpApiBuilder.group(MobileHttpApi.Api, "mobile", (handlers) =>
  handlers
    .handleRaw("authTokenList", forward)
    .handleRaw("authTokenCreate", forward)
    .handleRaw("authTokenRevoke", forward)
    .handleRaw("bootstrap", forward)
    .handleRaw("commandList", forward)
    .handleRaw("projectList", forward)
    .handleRaw("memoryHistory", forward)
    .handleRaw("memorySearch", forward)
    .handleRaw("memoryStashList", forward)
    .handleRaw("memoryStashCreate", forward)
    .handleRaw("memoryStashDelete", forward)
    .handleRaw("githubRepos", forward)
    .handleRaw("githubBranches", forward)
    .handleRaw("githubImports", forward)
    .handleRaw("githubOauthClient", forward)
    .handleRaw("githubOauthDeviceStart", forward)
    .handleRaw("githubOauthDevicePoll", forward)
    .handleRaw("githubAuthSet", forward)
    .handleRaw("githubAuthRemove", forward)
    .handleRaw("githubImport", forward)
    .handleRaw("githubSessionCreate", forward)
    .handleRaw("sessionList", forward)
    .handleRaw("sessionCreate", forward)
    .handleRaw("sessionDetail", forward)
    .handleRaw("sessionDelete", forward)
    .handleRaw("sessionDiff", forward)
    .handleRaw("sessionCommandList", forward)
    .handleRaw("sessionCommand", forward)
    .handleRaw("sessionMessage", forward)
    .handleRaw("sessionAbort", forward)
    .handleRaw("permissionRespond", forward)
    .handleRaw("questionRespond", forward)
    .handleRaw("questionReject", forward)
    .handleRaw("sessionPublish", forward)
    .handleRaw("sessionCleanup", forward)
    .handleRaw("sessionStream", forward)
    .handleRaw("sessionRename", forward)
    .handleRaw("teleportUploadBegin", forward)
    .handleRaw("teleportUploadChunk", forward)
    .handleRaw("teleportIn", forward)
    .handleRaw("teleportOut", forward)
    .handleRaw("worktreeCreate", forward)
    .handleRaw("worktreeRemove", forward)
    .handleRaw("worktreeReset", forward)
    .handleRaw("gitStatus", forward)
    .handleRaw("gitDiff", forward)
    .handleRaw("gitCommits", forward)
    .handleRaw("gitBranches", forward)
    .handleRaw("gitCommit", forward)
    .handleRaw("gitCheckout", forward)
    .handleRaw("gitStage", forward)
    .handleRaw("gitUnstage", forward)
    .handleRaw("gitDiscard", forward)
    .handleRaw("gitPush", forward)
    .handleRaw("gitPull", forward)
    .handleRaw("loopList", forward)
    .handleRaw("loopCreate", forward)
    .handleRaw("loopTemplates", forward)
    .handleRaw("loopGenerate", forward)
    .handleRaw("loopRunsRecent", forward)
    .handleRaw("loopGet", forward)
    .handleRaw("loopDelete", forward)
    .handleRaw("loopUpdate", forward)
    .handleRaw("loopRuns", forward)
    .handleRaw("loopRun", forward)
    .handleRaw("loopAbort", forward)
    .handleRaw("loopToggle", forward)
    .handleRaw("loopPause", forward)
    .handleRaw("loopResume", forward)
    .handleRaw("missionList", forward)
    .handleRaw("missionCreate", forward)
    .handleRaw("missionTemplates", forward)
    .handleRaw("missionGenerate", forward)
    .handleRaw("missionExecsRecent", forward)
    .handleRaw("missionGet", forward)
    .handleRaw("missionUpdate", forward)
    .handleRaw("missionDelete", forward)
    .handleRaw("missionExecs", forward)
    .handleRaw("missionStart", forward)
    .handleRaw("missionPause", forward)
    .handleRaw("missionCancel", forward)
    .handleRaw("missionFeatureMutate", forward)
    .handleRaw("events", forward)
    .handleRaw("brainStatus", forward)
    .handleRaw("brainTrigger", forward)
    .handleRaw("chatBotList", forward)
    .handleRaw("chatBotStart", forward)
    .handleRaw("chatBotStop", forward)
    .handleRaw("observabilityGet", forward)
    .handleRaw("observabilitySet", forward)
    .handleRaw("lspStatus", forward)
    .handleRaw("fusionList", forward)
    .handleRaw("fusionSet", forward)
    .handleRaw("hostBrowser", forward)
    .handleRaw("hostComputer", forward)
    .handleRaw("hostHerdrGet", forward)
    .handleRaw("hostHerdrSet", forward)
    .handleRaw("hostIsland", forward)
    .handleRaw("hostDevtools", forward)
    .handleRaw("sessionTodo", forward)
    .handleRaw("routineList", forward)
    .handleRaw("routineCreate", forward)
    .handleRaw("routineGet", forward)
    .handleRaw("routineDelete", forward)
    .handleRaw("routineUpdate", forward)
    .handleRaw("routineRun", forward)
    .handleRaw("routinePause", forward)
    .handleRaw("routineResume", forward)
    .handleRaw("routineTrigger", forward)
    .handleRaw("ptyList", forward)
    .handleRaw("ptyCreate", forward)
    .handleRaw("ptyGet", forward)
    .handleRaw("ptyUpdate", forward)
    .handleRaw("ptyRemove", forward)
    .handleRaw("ptyConnect", forward),
)
