/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

import "sst"
declare module "sst" {
  export interface Resource {
    "ADMIN_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_ACCESS_KEY_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "AWS_SES_SECRET_ACCESS_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DISCORD_SUPPORT_CHANNEL_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "database": string
      "host": string
      "password": string
      "port": number
      "type": "sst.sst.Linkable"
      "username": string
    }
    "EMAILOCTOPUS_API_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FEISHU_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "FEISHU_APP_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_ID": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_APP_PRIVATE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_ID_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "GITHUB_CLIENT_SECRET_CONSOLE": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NIKCLI_DISCORD_WEBHOOK_URL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NIKCLI_FIGMA_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NIKCLI_GITHUB_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NIKCLI_SLACK_BOT_TOKEN": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "NIKCLI_SLACK_CHANNEL": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2AccessKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "R2SecretKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_PUBLISHABLE_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_SECRET_KEY": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "STRIPE_WEBHOOK_SECRET": {
      "type": "sst.sst.Linkable"
      "value": string
    }
    "ZEN_BLACK": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS1": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS2": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS3": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS4": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS5": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS6": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS7": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_MODELS8": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "ZEN_SESSION_SECRET": {
      "type": "sst.sst.Secret"
      "value": string
    }
  }
}
// cloudflare 
import * as cloudflare from "@cloudflare/workers-types";
declare module "sst" {
  export interface Resource {
    "AuthStorage": cloudflare.KVNamespace
    "EnterpriseStorage": cloudflare.R2Bucket
    "GatewayKv": cloudflare.KVNamespace
    "LogProcessor": cloudflare.Service
  }
}

import "sst"
export {}