/**
 * Inlines web-client assets (template + styles + script) into a single TS module.
 * Run from package root: bun run scripts/inline-web-client.ts
 */
import { readFileSync, writeFileSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const __dirname = dirname(fileURLToPath(import.meta.url))
const pkgRoot = join(__dirname, "..")
const clientDir = join(pkgRoot, "src", "web-client")
const outPath = join(pkgRoot, "src", "web-client.generated.ts")

const template = readFileSync(join(clientDir, "template.html"), "utf-8")
const styles = readFileSync(join(clientDir, "styles.css"), "utf-8")
const script = readFileSync(join(clientDir, "app.js"), "utf-8")

const html = template
  .replace("{{STYLES}}", styles)
  .replace("{{SCRIPT}}", script)

// Escape for embedding in a TS template literal: backslash and backtick
const escaped = html.replace(/\\/g, "\\\\").replace(/`/g, "\\`")

const generated = `// Generated by scripts/inline-web-client.ts - do not edit by hand
export const WEB_CLIENT_HTML = \`${escaped}\`;
`

writeFileSync(outPath, generated, "utf-8")
console.log("Wrote", outPath)
