name: release-github-action

on:
  push:
    branches:
      - live-main
    paths:
      - "github/**"

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - run: git fetch --force --tags

      - name: Release
        run: |
          git config --global user.email "nicola.mattioli.95@gmail.com"
          git config --global user.name "nikomatt69"
          ./github/script/release
