#!/usr/bin/env bun
import { $ } from "bun"
import { Script } from "@nikcli-ai/script"

if (!Script.preview) {
  // Calculate SHA values
  const arm64Sha = await $`sha256sum ./dist/nikcli-linux-arm64.tar.gz | cut -d' ' -f1`.text().then((x) => x.trim())
  const x64Sha = await $`sha256sum ./dist/nikcli-linux-x64.tar.gz | cut -d' ' -f1`.text().then((x) => x.trim())
  const macX64Sha = await $`sha256sum ./dist/nikcli-darwin-x64.zip | cut -d' ' -f1`.text().then((x) => x.trim())
  const macArm64Sha = await $`sha256sum ./dist/nikcli-darwin-arm64.zip | cut -d' ' -f1`.text().then((x) => x.trim())

  // Homebrew formula
  const homebrewFormula = [
    "# typed: false",
    "# frozen_string_literal: true",
    "",
    "# This file was generated by GoReleaser. DO NOT EDIT.",
    "class Nikcli < Formula",
    `  desc "The AI coding agent built for the terminal."`,
    `  homepage "https://github.com/nikomatt69/nikcli"`,
    `  version "${Script.version.split("-")[0]}"`,
    "",
    "",
    "  on_macos do",
    "    if Hardware::CPU.intel?",
    `      url "https://github.com/nikomatt69/nikcli/releases/download/v${Script.version}/nikcli-darwin-x64.zip"`,
    `      sha256 "${macX64Sha}"`,
    "",
    "      def install",
    '        bin.install "nikcli"',
    "      end",
    "    end",
    "    if Hardware::CPU.arm?",
    `      url "https://github.com/nikomatt69/nikcli/releases/download/v${Script.version}/nikcli-darwin-arm64.zip"`,
    `      sha256 "${macArm64Sha}"`,
    "",
    "      def install",
    '        bin.install "nikcli"',
    "      end",
    "    end",
    "  end",
    "",
    "  on_linux do",
    "    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?",
    `      url "https://github.com/nikomatt69/nikcli/releases/download/v${Script.version}/nikcli-linux-x64.tar.gz"`,
    `      sha256 "${x64Sha}"`,
    "      def install",
    '        bin.install "nikcli"',
    "      end",
    "    end",
    "    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?",
    `      url "https://github.com/nikomatt69/nikcli/releases/download/v${Script.version}/nikcli-linux-arm64.tar.gz"`,
    `      sha256 "${arm64Sha}"`,
    "      def install",
    '        bin.install "nikcli"',
    "      end",
    "    end",
    "  end",
    "end",
    "",
    "",
  ].join("\n")

  await $`rm -rf ./dist/homebrew-tap`
  await $`git clone https://${process.env["GITHUB_TOKEN"]}@github.com/sst/homebrew-tap.git ./dist/homebrew-tap`
  await Bun.file("./dist/homebrew-tap/nikcli.rb").write(homebrewFormula)
  await $`cd ./dist/homebrew-tap && git add nikcli.rb`
  await $`cd ./dist/homebrew-tap && git commit -m "Update to v${Script.version}"`
  await $`cd ./dist/homebrew-tap && git push`
}
